'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  changeLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    // Hero Section
    'hero.subtitle': 'Özel anlarınız için kişiselleştirilmiş şarkılar yaratın. Düğünlerden doğum günlerine kadar, her kutlamayı unutulmaz kılın.',
    'hero.button': 'Ücretsiz Başla',
    'hero.process': 'Basit: Prompt → Oluştur → Öde → Keyfet',
    
    // Navigation
    'nav.services': 'Hizmetler',
    'nav.howItWorks': 'Nasıl Çalışır',
    'nav.songRequest': 'Şarkı Talebi',
    'nav.voiceCloning': 'Ses Klonlama',
    'nav.videoRequest': 'Video Talebi',
    'nav.getStarted': 'Başla',
    
    // Services
    'services.title': 'Hizmetlerimiz ve Fiyatlandırma',
    'services.subtitle': 'Ücretsiz başlayın! 3 ücretsiz şarkı oluşturma hakkı kazanın, sonra kullanım başına ödeme yapın.',
    'services.freeTier.title': 'Ücretsiz Şarkı Oluşturma',
    'services.freeTier.description': 'Her yeni kullanıcı, AI destekli platformumuzu deneyimlemek için 3 ÜCRETSİZ şarkı oluşturma hakkı kazanır.',
    'services.freeTier.step1': 'İlk şarkınızı oluşturun',
    'services.freeTier.step2': 'Mükemmelleştirin ve geliştirin',
    'services.freeTier.step3': 'Yaratımınızı mükemmelleştirin',
    
    // Service Details
    'services.songCreation.title': 'Özel Şarkı Oluşturma',
    'services.songCreation.description': 'Özel anlarınız için AI destekli kişiselleştirilmiş şarkılar',
    'services.songCreation.price': 'Ücretsiz',
    'services.songCreation.priceNote': 'İlk 3 şarkı',
    'services.songCreation.feature1': 'Özel sözler ve melodi',
    'services.songCreation.feature2': 'Çoklu tür seçenekleri',
    'services.songCreation.feature3': 'Şarkı başına 3 revizyon',
    'services.songCreation.feature4': 'Yüksek kaliteli ses dosyası',
    'services.songCreation.feature5': 'Kişisel kullanım hakları',
    'services.songCreation.feature6': '7 gün içinde teslimat',
    
    'services.voiceCloning.title': 'Ses Klonlama',
    'services.voiceCloning.description': 'Şarkı söylemek için sesinizin mükemmel bir kopyasını oluşturun',
    'services.voiceCloning.price': '250 TL',
    'services.voiceCloning.priceNote': 'ses klonu başına',
    'services.voiceCloning.feature1': 'Profesyonel ses analizi',
    'services.voiceCloning.feature2': 'Yüksek kaliteli ses klonu',
    'services.voiceCloning.feature3': 'Çoklu ses varyasyonları',
    'services.voiceCloning.feature4': 'Eğitim verisi dahil',
    'services.voiceCloning.feature5': 'Gelecekteki kullanım için API erişimi',
    'services.voiceCloning.feature6': '14 gün içinde teslimat',
    
    'services.videoAnimation.title': 'Fotoğraf/Video Animasyonu',
    'services.videoAnimation.description': 'Fotoğraflarınızı AI animasyonu ile hayata geçirin',
    'services.videoAnimation.price': '500 TL',
    'services.videoAnimation.priceNote': 'video başına',
    'services.videoAnimation.feature1': 'AI destekli animasyon',
    'services.videoAnimation.feature2': 'Çoklu stil seçenekleri',
    'services.videoAnimation.feature3': 'Özel video senaryoları',
    'services.videoAnimation.feature4': 'Yüksek çözünürlüklü çıktı',
    'services.videoAnimation.feature5': 'Çoklu format desteği',
    'services.videoAnimation.feature6': '10 gün içinde teslimat',
    
    // Pricing
    'pricing.freeTier.name': 'Ücretsiz Paket',
    'pricing.freeTier.price': 'Ücretsiz',
    'pricing.freeTier.description': 'Hizmetimizi denemek için mükemmel',
    'pricing.freeTier.feature1': '3 ücretsiz şarkı oluşturma',
    'pricing.freeTier.feature2': 'Temel özelleştirme seçenekleri',
    'pricing.freeTier.feature3': 'Standart kalite çıktısı',
    'pricing.freeTier.feature4': 'E-posta desteği',
    'pricing.freeTier.feature5': '7 günlük teslimat',
    'pricing.freeTier.button': 'Ücretsiz Oluşturmaya Başla',
    
    'pricing.payPerUse.name': 'Kullanım Başına Ödeme',
    'pricing.payPerUse.price': 'Değişken',
    'pricing.payPerUse.description': 'Sadece ihtiyacınız olan için ödeyin',
    'pricing.payPerUse.feature1': 'Ek şarkılar: her biri 500 TL',
    'pricing.payPerUse.feature2': 'Ses klonlama: her biri 250 TL',
    'pricing.payPerUse.feature3': 'Video animasyonu: her biri 500 TL',
    'pricing.payPerUse.feature4': 'Premium kalite çıktısı',
    'pricing.payPerUse.feature5': 'Standart destek',
    'pricing.payPerUse.feature6': '7 günlük teslimat',
    'pricing.payPerUse.button': 'Kullanım Başına Öde',
    
    // Payment Information
    'payment.title': 'Ödeme Bilgileri',
    'payment.description': 'Ödeme, ilk üç ücretsiz adım tamamlandıktan sonra alınır. Türk Lirası (TL) ile ödeme kabul ediyoruz.',
    'payment.pricing.title': 'Hizmet Fiyatlandırması (TL)',
    'payment.songGeneration': 'Şarkı Oluşturma: 500 TL',
    'payment.voiceCloning': 'Ses Klonlama: 250 TL',
    'payment.videoCreation': 'Video Oluşturma: 500 TL',
    'payment.gateways.title': 'Ödeme Geçitleri',
    'payment.iyzico': 'Güvenli Türk ödeme geçidi',
    'payment.paytr': 'Alternatif Türk ödeme çözümü',
    'payment.comingSoon': 'Yakında',
    'payment.accountsOpening': 'Ödeme hesapları şu anda açılıyor',
    
    // How It Works
    'howItWorks.title': 'Nasıl Çalışır',
    'howItWorks.subtitle': 'Sadece 3 basit adımda özel şarkınızı oluşturun',
    'howItWorks.step1.title': 'Şarkınızı Oluşturun',
    'howItWorks.step1.description': 'Vizyonunuzu tanımlayın ve AI\'nın mükemmel şarkınızı yaratmasına izin verin',
    'howItWorks.step1.detail1': 'Özel anınızı tanımlayın',
    'howItWorks.step1.detail2': 'Hikayenizi ve duygularınızı paylaşın',
    'howItWorks.step1.detail3': 'Tercih ettiğiniz stili seçin',
    'howItWorks.step2.title': 'Sesinizi Klonlayın',
    'howItWorks.step2.description': 'Bir örnek yükleyin ve benzersiz ses klonunuzu alın',
    'howItWorks.step2.detail1': 'Ses örneğinizi yükleyin',
    'howItWorks.step2.detail2': 'AI analizi yapılsın',
    'howItWorks.step2.detail3': 'Mükemmel ses klonunuzu alın',
    'howItWorks.step3.title': 'Fotoğraflarınızı Canlandırın',
    'howItWorks.step3.description': 'Statik görüntüleri dinamik videolara dönüştürün',
    'howItWorks.step3.detail1': 'Fotoğrafınızı yükleyin',
    'howItWorks.step3.detail2': 'Animasyon stilini seçin',
    'howItWorks.step3.detail3': 'Canlı videonuzu alın',
    'howItWorks.learnMore': 'Daha Fazla Bilgi',
    'howItWorks.cta.title': 'Hemen Başlayın',
    'howItWorks.cta.description': 'Özel anlarınızı unutulmaz kılmaya hazır mısınız?',
    'howItWorks.cta.button': 'Ücretsiz Oluşturmaya Başla',
    
    // Footer
    'footer.description': 'Özel anlarınızı unutulmaz kılan kişiselleştirilmiş şarkılar ve videolar oluşturuyoruz. Suno API, KITS AI ve RunwayML dahil en son AI teknolojisi ile desteklenmektedir.',
    'footer.location': 'İstanbul, Türkiye',
    'footer.copyright': '© 2024 SongCreator. Tüm hakları saklıdır.',
    'footer.categories.services': 'Hizmetler',
    'footer.categories.company': 'Şirket',
    'footer.categories.support': 'Destek',
    'footer.categories.resources': 'Kaynaklar',
    'footer.services.songCreation': 'Özel Şarkı Oluşturma',
    'footer.services.voiceCloning': 'Ses Klonlama',
    'footer.services.videoAnimation': 'Fotoğraf/Video Animasyonu',

    'footer.company.aboutUs': 'Hakkımızda',

    'footer.company.contact': 'İletişim',
    'footer.support.helpCenter': 'Yardım Merkezi',
    'footer.support.termsOfService': 'Kullanım Şartları',
    'footer.support.privacyPolicy': 'Gizlilik Politikası',


    'footer.resources.examplesGallery': 'Örnekler Galerisi',
    'footer.resources.pricingCalculator': 'Fiyat Hesaplayıcısı',
    
    // Song Form
    'songForm.title': 'Mükemmel Şarkınızı Oluşturun',
    'songForm.subtitle': 'Vizyonunuzu anlatın, duygularınızı mükemmel şekilde yakalayan kişiselleştirilmiş bir şarkı oluşturalım.',
    'songForm.fields.fullName': 'Ad Soyad',
    'songForm.fields.email': 'E-posta',
    'songForm.fields.phone': 'Telefon Numarası',
    'songForm.fields.specialOccasion': 'Özel Gün',
    'songForm.fields.songStyle': 'Şarkı Stili',
    'songForm.fields.mood': 'Ruh Hali',
    'songForm.fields.tempo': 'Tempo',
    'songForm.fields.namesToInclude': 'Dahil Edilecek İsimler',
    'songForm.fields.yourStory': 'Hikayeniz',
    'songForm.fields.additionalNotes': 'Ek Notlar',
    'songForm.placeholders.fullName': 'Adınızı ve soyadınızı girin',
    'songForm.placeholders.email': 'your.email@example.com',
    'songForm.placeholders.phone': '+32651544223',
    'songForm.placeholders.selectOccasion': 'Bir gün seçin',
    'songForm.placeholders.chooseStyle': 'Bir stil seçin',
    'songForm.placeholders.selectMood': 'Ruh halini seçin',
    'songForm.placeholders.chooseTempo': 'Tempo seçin',
    'songForm.placeholders.namesToInclude': 'örn. Sarah & John, Anne & Baba',
    'songForm.placeholders.yourStory': 'Bu şarkının arkasındaki hikayeyi anlatın. Ne onu özel kılıyor? Hangi duyguları yakalamak istiyorsunuz?',
    'songForm.placeholders.additionalNotes': 'Dahil etmek istediğiniz özel sözler, referanslar veya özel istekler var mı?',
    'songForm.submitButton.submitting': 'Şarkınız Oluşturuluyor...',
    'songForm.submitButton.createSong': 'Şarkımı Oluştur',
    'songForm.submitButton.reviewTime': 'Talebinizi inceleyeceğiz ve 24 saat içinde size geri döneceğiz',
    
    // Voice Form
    'voiceForm.title': 'Sesinizi Klonlayın',
    'voiceForm.subtitle': 'Kendi klonlanmış sesinizle duygularınızı söyleyin. Bir örnek yükleyin ve mükemmel bir kopya oluşturalım.',
    'voiceForm.nameLabel': 'Ad Soyad *',
    'voiceForm.emailLabel': 'E-posta *',
    'voiceForm.purposeLabel': 'Ses Klonlama Amacı *',
    'voiceForm.audioSampleLabel': 'Ses Örneği *',
    'voiceForm.additionalNotesLabel': 'Ek Notlar',
    'voiceForm.namePlaceholder': 'Adınızı ve soyadınızı girin',
    'voiceForm.emailPlaceholder': 'your.email@example.com',
    'voiceForm.selectPurpose': 'Amacı seçin',
    'voiceForm.uploadAudioPrompt': 'Ses örneğinizi yükleyin',
    'voiceForm.supportedFormats': 'Desteklenen formatlar: MP3, WAV, M4A (Maksimum 10MB)',
    'voiceForm.chooseAudioFile': 'Ses Dosyası Seç',
    'voiceForm.changeFile': 'Dosyayı Değiştir',
    'voiceForm.removeFile': 'Kaldır',
    'voiceForm.audioNotSupported': 'Tarayıcınız ses öğesini desteklemiyor.',
    'voiceForm.requirements': 'Gereksinimler:',
    'voiceForm.requirementsDescription': 'Net konuşma/şarkı, minimal arka plan gürültüsü, 30+ saniye önerilir',
    'voiceForm.additionalNotesPlaceholder': 'Ses klonlama projeniz hakkında özel gereksinimler veya notlar...',
    'voiceForm.dataPrivacyTitle': 'Veri Gizliliği ve Onay',
    'voiceForm.dataPrivacyDescription': 'Ses örneğinizi sağlayarak, ses verilerinizin işlenmesi ve saklanmasına, ses klonu oluşturma amacıyla onay veriyorsunuz. Verileriniz GDPR düzenlemelerine uygun olarak işlenecek ve yalnızca belirtilen amaç için kullanılacaktır. Verilerinizin silinmesini isteme hakkına sahipsiniz.',
    'voiceForm.gdprConsent': 'Ses klonlama amaçları için ses verilerimin işlenmesine ve saklanmasına onay veriyorum ve GDPR düzenlemeleri kapsamındaki haklarımı anlıyorum.',
    'voiceForm.consentAlert': 'Lütfen veri saklama ve işleme için onay verin.',
    'voiceForm.processingMessage': 'Talebiniz İşleniyor...',
    'voiceForm.startVoiceCloning': 'Ses Klonlamaya Başla',
    'voiceForm.responseTime': 'Ses örneğinizi analiz edeceğiz ve 48 saat içinde size geri döneceğiz',
    'voiceForm.purposes.personal': 'Kişisel şarkı kaydı',
    'voiceForm.purposes.podcast': 'Podcast anlatımı',
    'voiceForm.purposes.audiobook': 'Sesli kitap anlatımı',
    'voiceForm.purposes.voiceActing': 'Seslendirme',
    'voiceForm.purposes.assistant': 'Kişisel asistan sesi',
    'voiceForm.purposes.other': 'Diğer',
    
    // Photo/Video Form
    'photoVideoForm.bringYourPhotos': 'Fotoğraflarınızı Canlandırın',
    'photoVideoForm.turnYourPhotosIntoMovingVideos': 'Fotoğraflarınızı hareketli videolara dönüştürün ve AI destekli animasyonla etkileyici müzik video klipleri oluşturun.',
    'photoVideoForm.fullName': 'Ad Soyad *',
    'photoVideoForm.email': 'E-posta *',
    'photoVideoForm.photosVideos': 'Fotoğraflar ve Videolar *',
    'photoVideoForm.animationStyle': 'Animasyon Stili',
    'photoVideoForm.desiredDuration': 'İstenen Süre',
    'photoVideoForm.animationPrompt': 'Animasyon İsteği *',
    'photoVideoForm.videoScenario': 'Video Senaryosu',
    'photoVideoForm.additionalNotes': 'Ek Notlar',
    'photoVideoForm.enterYourFullName': 'Adınızı ve soyadınızı girin',
    'photoVideoForm.yourEmailExample': 'your.email@example.com',
    'photoVideoForm.uploadYourPhotosVideos': 'Fotoğraf ve videolarınızı yükleyin',
    'photoVideoForm.supportedFormats': 'Desteklenen formatlar: JPG, PNG, MP4, MOV (Toplam maksimum 50MB)',
    'photoVideoForm.chooseFiles': 'Dosya Seç',
    'photoVideoForm.addMoreFiles': 'Daha Fazla Dosya Ekle',
    'photoVideoForm.requirements': 'Gereksinimler',
    'photoVideoForm.highQualityImagesVideos': 'Yüksek kaliteli görüntüler/videolar, iyi aydınlatma, net konular',
    'photoVideoForm.chooseAstyle': 'Bir stil seçin',
    'photoVideoForm.selectDuration': 'Süre seçin',
    'photoVideoForm.describeHowYouWantYourPhotosToMove': 'Fotoğraflarınızın nasıl hareket etmesini ve canlanmasını istediğinizi açıklayın. Hareketler, efektler ve geçişler hakkında spesifik olun...',
    'photoVideoForm.describeTheOverallVideoConcept': 'Oluşturmak istediğiniz genel video konseptini, hikayeyi veya ruh halini açıklayın...',
    'photoVideoForm.anySpecificRequirements': 'Videonuz için özel gereksinimler, referanslar veya özel istekler...',
    'photoVideoForm.dataPrivacyConsent': 'Veri Gizliliği ve Onay',
    'photoVideoForm.consentDescription': 'Medya dosyalarınızı yükleyerek, animasyonlu video oluşturma amacıyla içeriğinizin işlenmesine ve saklanmasına onay veriyorsunuz. Verileriniz GDPR düzenlemelerine uygun olarak işlenecek ve yalnızca belirtilen amaç için kullanılacaktır. Verilerinizin silinmesini isteme hakkına sahipsiniz.',
    'photoVideoForm.consentCheckboxText': 'Video oluşturma amaçları için medya dosyalarımın işlenmesine ve saklanmasına onay veriyorum ve GDPR düzenlemeleri kapsamındaki haklarımı anlıyorum. *',
    'photoVideoForm.consentAlert': 'Lütfen veri saklama ve işleme için onay verin.',
    'photoVideoForm.processingYourRequest': 'Talebiniz İşleniyor...',
    'photoVideoForm.createMyVideo': 'Videomu Oluştur',
    'photoVideoForm.reviewYourRequest': 'Talebinizi inceleyeceğiz ve 48 saat içinde size geri döneceğiz',
    'photoVideoForm.styles.cinematic': 'Sinematik',
    'photoVideoForm.styles.romantic': 'Romantik',
    'photoVideoForm.styles.adventure': 'Macera',
    'photoVideoForm.styles.fantasy': 'Fantastik',
    'photoVideoForm.styles.documentary': 'Belgesel',
    'photoVideoForm.styles.artistic': 'Sanatsal',
    'photoVideoForm.styles.modern': 'Modern',
    'photoVideoForm.styles.vintage': 'Vintage',
    'photoVideoForm.styles.minimalist': 'Minimalist',
    'photoVideoForm.styles.dynamic': 'Dinamik',
    'photoVideoForm.durations.short': '15-30 saniye',
    'photoVideoForm.durations.medium': '30-60 saniye',
    'photoVideoForm.durations.long': '1-2 dakika',
    'photoVideoForm.durations.mediumLong': '2-3 dakika',
    'photoVideoForm.durations.longer': '3-5 dakika',
  },
  en: {
    // Hero Section
    'hero.subtitle': 'Create personalized songs for your special moments. From weddings to birthdays, make every celebration unforgettable with your own unique soundtrack.',
    'hero.button': 'Start Free',
    'hero.process': 'It\'s simple: Prompt → Generate → Pay → Enjoy',
    
    // Navigation
    'nav.services': 'Services',
    'nav.howItWorks': 'How It Works',
    'nav.songRequest': 'Song Request',
    'nav.voiceCloning': 'Voice Cloning',
    'nav.videoRequest': 'Video Request',
    'nav.getStarted': 'Get Started',
    
    // Services
    'services.title': 'Our Services & Pricing',
    'services.subtitle': 'Start creating for free! Get 3 free song creations, then pay per use.',
    'services.freeTier.title': 'Free Song Creation',
    'services.freeTier.description': 'Every new user gets 3 FREE song creations to experience our AI-powered platform.',
    'services.freeTier.step1': 'Create your first song',
    'services.freeTier.step2': 'Refine and improve',
    'services.freeTier.step3': 'Perfect your creation',
    
    // Service Details
    'services.songCreation.title': 'Custom Song Creation',
    'services.songCreation.description': 'AI-powered personalized songs for your special moments',
    'services.songCreation.price': 'Free',
    'services.songCreation.priceNote': 'First 3 songs',
    'services.songCreation.feature1': 'Custom lyrics and melody',
    'services.songCreation.feature2': 'Multiple genre options',
    'services.songCreation.feature3': 'Up to 3 revisions per song',
    'services.songCreation.feature4': 'High-quality audio file',
    'services.songCreation.feature5': 'Personal usage rights',
    'services.songCreation.feature6': 'Delivery within 7 days',
    
    'services.voiceCloning.title': 'Voice Cloning',
    'services.voiceCloning.description': 'Create a perfect replica of your voice for singing',
    'services.voiceCloning.price': '250 TL',
    'services.voiceCloning.priceNote': 'per voice clone',
    'services.voiceCloning.feature1': 'Professional voice analysis',
    'services.voiceCloning.feature2': 'High-fidelity voice clone',
    'services.voiceCloning.feature3': 'Multiple voice variations',
    'services.voiceCloning.feature4': 'Training data included',
    'services.voiceCloning.feature5': 'API access for future use',
    'services.voiceCloning.feature6': 'Delivery within 14 days',
    
    'services.videoAnimation.title': 'Photo/Video Animation',
    'services.videoAnimation.description': 'Bring your photos to life with AI animation',
    'services.videoAnimation.price': '500 TL',
    'services.videoAnimation.priceNote': 'per video',
    'services.videoAnimation.feature1': 'AI-powered animation',
    'services.videoAnimation.feature2': 'Multiple style options',
    'services.videoAnimation.feature3': 'Custom video scenarios',
    'services.videoAnimation.feature4': 'High-resolution output',
    'services.videoAnimation.feature5': 'Multiple format support',
    'services.videoAnimation.feature6': 'Delivery within 10 days',
    
    // Pricing
    'pricing.freeTier.name': 'Free Tier',
    'pricing.freeTier.price': 'Free',
    'pricing.freeTier.description': 'Perfect for trying out our service',
    'pricing.freeTier.feature1': '3 free song creations',
    'pricing.freeTier.feature2': 'Basic customization options',
    'pricing.freeTier.feature3': 'Standard quality output',
    'pricing.freeTier.feature4': 'Email support',
    'pricing.freeTier.feature5': '7-day delivery',
    'pricing.freeTier.button': 'Start Creating Free',
    
    'pricing.payPerUse.name': 'Pay Per Use',
    'pricing.payPerUse.price': 'Variable',
    'pricing.payPerUse.description': 'Pay only for what you need',
    'pricing.payPerUse.feature1': 'Additional songs: 500 TL each',
    'pricing.payPerUse.feature2': 'Voice cloning: 250 TL each',
    'pricing.payPerUse.feature3': 'Video animation: 500 TL each',
    'pricing.payPerUse.feature4': 'Premium quality output',
    'pricing.payPerUse.feature5': 'Standard support',
    'pricing.payPerUse.feature6': '7-day delivery',
    'pricing.payPerUse.button': 'Pay Per Use',
    
    // Payment Information
    'payment.title': 'Payment Information',
    'payment.description': 'Payment is received after the first three free steps are completed. We accept payments in Turkish Lira (TL).',
    'payment.pricing.title': 'Service Pricing (TL)',
    'payment.songGeneration': 'Song Generation: 500 TL',
    'payment.voiceCloning': 'Voice Cloning: 250 TL',
    'payment.videoCreation': 'Video Creation: 500 TL',
    'payment.gateways.title': 'Payment Gateways',
    'payment.iyzico': 'Secure Turkish payment gateway',
    'payment.paytr': 'Alternative Turkish payment solution',
    'payment.comingSoon': 'Coming Soon',
    'payment.accountsOpening': 'Payment accounts are currently being opened',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Create your custom song in just 3 simple steps',
    'howItWorks.step1.title': 'Create Your Song',
    'howItWorks.step1.description': 'Describe your vision and let AI create your perfect song',
    'howItWorks.step1.detail1': 'Describe your special moment',
    'howItWorks.step1.detail2': 'Share your story and emotions',
    'howItWorks.step1.detail3': 'Choose your preferred style',
    'howItWorks.step2.title': 'Clone Your Voice',
    'howItWorks.step2.description': 'Upload a sample and get your unique voice clone',
    'howItWorks.step2.detail1': 'Upload your voice sample',
    'howItWorks.step2.detail2': 'AI analysis is performed',
    'howItWorks.step2.detail3': 'Get your perfect voice clone',
    'howItWorks.step3.title': 'Animate Your Photos',
    'howItWorks.step3.description': 'Turn static images into dynamic videos',
    'howItWorks.step3.detail1': 'Upload your photo',
    'howItWorks.step3.detail2': 'Choose animation style',
    'howItWorks.step3.detail3': 'Get your live video',
    'howItWorks.learnMore': 'Learn More',
    'howItWorks.cta.title': 'Get Started Now',
    'howItWorks.cta.description': 'Ready to make your special moments unforgettable?',
    'howItWorks.cta.button': 'Start Creating Free',
    
    // Footer
    'footer.description': 'We create personalized songs and videos that make your special moments unforgettable. Powered by the latest AI technologies including Suno API, KITS AI, and RunwayML.',
    'footer.location': 'Istanbul, Turkey',
    'footer.copyright': '© 2024 SongCreator. All rights reserved.',
    'footer.categories.services': 'Services',
    'footer.categories.company': 'Company',
    'footer.categories.support': 'Support',
    'footer.categories.resources': 'Resources',
    'footer.services.songCreation': 'Custom Song Creation',
    'footer.services.voiceCloning': 'Voice Cloning',
    'footer.services.videoAnimation': 'Photo/Video Animation',

    'footer.company.aboutUs': 'About Us',

    'footer.company.contact': 'Contact',
    'footer.support.helpCenter': 'Help Center',
    'footer.support.termsOfService': 'Terms of Service',
    'footer.support.privacyPolicy': 'Privacy Policy',


    'footer.resources.examplesGallery': 'Examples Gallery',
    'footer.resources.pricingCalculator': 'Pricing Calculator',
    
    // Song Form
    'songForm.title': 'Create Your Perfect Song',
    'songForm.subtitle': 'Tell us about your vision and we\'ll create a personalized song that captures your emotions perfectly.',
    'songForm.fields.fullName': 'Full Name',
    'songForm.fields.email': 'Email',
    'songForm.fields.phone': 'Phone Number',
    'songForm.fields.specialOccasion': 'Special Occasion',
    'songForm.fields.songStyle': 'Song Style',
    'songForm.fields.mood': 'Mood',
    'songForm.fields.tempo': 'Tempo',
    'songForm.fields.namesToInclude': 'Names to Include',
    'songForm.fields.yourStory': 'Your Story',
    'songForm.fields.additionalNotes': 'Additional Notes',
    'songForm.placeholders.fullName': 'Enter your full name',
    'songForm.placeholders.email': 'your.email@example.com',
    'songForm.placeholders.phone': '+32651544223',
    'songForm.placeholders.selectOccasion': 'Select an occasion',
    'songForm.placeholders.chooseStyle': 'Choose a style',
    'songForm.placeholders.selectMood': 'Select the mood',
    'songForm.placeholders.chooseTempo': 'Choose tempo',
    'songForm.placeholders.namesToInclude': 'e.g., Sarah & John, Mom & Dad',
    'songForm.placeholders.yourStory': 'Tell us the story behind this song. What makes it special? What emotions do you want to capture?',
    'songForm.placeholders.additionalNotes': 'Any specific lyrics, references, or special requests you\'d like to include?',
    'songForm.submitButton.submitting': 'Creating Your Song...',
    'songForm.submitButton.createSong': 'Create My Song',
    'songForm.submitButton.reviewTime': 'We\'ll review your request and get back to you within 24 hours',
    
    // Voice Form
    'voiceForm.title': 'Clone Your Voice',
    'voiceForm.subtitle': 'Sing your feelings with your own cloned voice. Upload a sample and we\'ll create a perfect replica.',
    'voiceForm.nameLabel': 'Full Name *',
    'voiceForm.emailLabel': 'Email *',
    'voiceForm.purposeLabel': 'Purpose of Voice Cloning *',
    'voiceForm.audioSampleLabel': 'Audio Sample *',
    'voiceForm.additionalNotesLabel': 'Additional Notes',
    'voiceForm.namePlaceholder': 'Enter your full name',
    'voiceForm.emailPlaceholder': 'your.email@example.com',
    'voiceForm.selectPurpose': 'Select the purpose',
    'voiceForm.uploadAudioPrompt': 'Upload your audio sample',
    'voiceForm.supportedFormats': 'Supported formats: MP3, WAV, M4A (Max 10MB)',
    'voiceForm.chooseAudioFile': 'Choose Audio File',
    'voiceForm.changeFile': 'Change File',
    'voiceForm.removeFile': 'Remove',
    'voiceForm.audioNotSupported': 'Your browser does not support the audio element.',
    'voiceForm.requirements': 'Requirements:',
    'voiceForm.requirementsDescription': 'Clear speech/singing, minimal background noise, 30+ seconds recommended',
    'voiceForm.additionalNotesPlaceholder': 'Any specific requirements or notes about your voice cloning project...',
    'voiceForm.dataPrivacyTitle': 'Data Privacy & Consent',
    'voiceForm.dataPrivacyDescription': 'By providing your audio sample, you consent to the processing and storage of your voice data for the purpose of creating a voice clone. Your data will be handled in accordance with GDPR regulations and will only be used for the specified purpose. You have the right to request deletion of your data at any time.',
    'voiceForm.gdprConsent': 'I consent to the processing and storage of my voice data for voice cloning purposes, and I understand my rights under GDPR regulations.',
    'voiceForm.consentAlert': 'Please provide consent for data storage and processing.',
    'voiceForm.processingMessage': 'Processing Your Request...',
    'voiceForm.startVoiceCloning': 'Start Voice Cloning',
    'voiceForm.responseTime': 'We\'ll analyze your audio and get back to you within 48 hours',
    'voiceForm.purposes.personal': 'Personal song recording',
    'voiceForm.purposes.podcast': 'Podcast narration',
    'voiceForm.purposes.audiobook': 'Audiobook narration',
    'voiceForm.purposes.voiceActing': 'Voice acting',
    'voiceForm.purposes.assistant': 'Personal assistant voice',
    'voiceForm.purposes.other': 'Other',
    
    // Photo/Video Form
    'photoVideoForm.bringYourPhotos': 'Bring Your Photos to Life',
    'photoVideoForm.turnYourPhotosIntoMovingVideos': 'Turn your photos into moving videos and create stunning music video clips with AI-powered animation.',
    'photoVideoForm.fullName': 'Full Name *',
    'photoVideoForm.email': 'Email *',
    'photoVideoForm.photosVideos': 'Photos & Videos *',
    'photoVideoForm.animationStyle': 'Animation Style',
    'photoVideoForm.desiredDuration': 'Desired Duration',
    'photoVideoForm.animationPrompt': 'Animation Prompt *',
    'photoVideoForm.videoScenario': 'Video Scenario',
    'photoVideoForm.additionalNotes': 'Additional Notes',
    'photoVideoForm.enterYourFullName': 'Enter your full name',
    'photoVideoForm.yourEmailExample': 'your.email@example.com',
    'photoVideoForm.uploadYourPhotosVideos': 'Upload your photos and videos',
    'photoVideoForm.supportedFormats': 'Supported formats: JPG, PNG, MP4, MOV (Max 50MB total)',
    'photoVideoForm.chooseFiles': 'Choose Files',
    'photoVideoForm.addMoreFiles': 'Add More Files',
    'photoVideoForm.requirements': 'Requirements',
    'photoVideoForm.highQualityImagesVideos': 'High quality images/videos, good lighting, clear subjects',
    'photoVideoForm.chooseAstyle': 'Choose a style',
    'photoVideoForm.selectDuration': 'Select duration',
    'photoVideoForm.describeHowYouWantYourPhotosToMove': 'Describe how you want your photos to move and animate. Be specific about movements, effects, and transitions...',
    'photoVideoForm.describeTheOverallVideoConcept': 'Describe the overall video concept, story, or mood you want to create...',
    'photoVideoForm.anySpecificRequirements': 'Any specific requirements, references, or special requests for your video...',
    'photoVideoForm.dataPrivacyConsent': 'Data Privacy & Consent',
    'photoVideoForm.consentDescription': 'By uploading your media files, you consent to the processing and storage of your content for the purpose of creating animated videos. Your data will be handled in accordance with GDPR regulations and will only be used for the specified purpose. You have the right to request deletion of your data at any time.',
    'photoVideoForm.consentCheckboxText': 'I consent to the processing and storage of my media files for video creation purposes, and I understand my rights under GDPR regulations. *',
    'photoVideoForm.consentAlert': 'Please provide consent for data storage and processing.',
    'photoVideoForm.processingYourRequest': 'Processing Your Request...',
    'photoVideoForm.createMyVideo': 'Create My Video',
    'photoVideoForm.reviewYourRequest': 'We\'ll review your request and get back to you within 48 hours',
    'photoVideoForm.styles.cinematic': 'Cinematic',
    'photoVideoForm.styles.romantic': 'Romantic',
    'photoVideoForm.styles.adventure': 'Adventure',
    'photoVideoForm.styles.fantasy': 'Fantasy',
    'photoVideoForm.styles.documentary': 'Documentary',
    'photoVideoForm.styles.artistic': 'Artistic',
    'photoVideoForm.styles.modern': 'Modern',
    'photoVideoForm.styles.vintage': 'Vintage',
    'photoVideoForm.styles.minimalist': 'Minimalist',
    'photoVideoForm.styles.dynamic': 'Dynamic',
    'photoVideoForm.durations.short': '15-30 seconds',
    'photoVideoForm.durations.medium': '30-60 seconds',
    'photoVideoForm.durations.long': '1-2 minutes',
    'photoVideoForm.durations.mediumLong': '2-3 minutes',
    'photoVideoForm.durations.longer': '3-5 minutes',
  },
  nl: {
    // Hero Section
    'hero.subtitle': 'Maak gepersonaliseerde liedjes voor je speciale momenten. Van bruiloften tot verjaardagen, maak elke viering onvergetelijk.',
    'hero.button': 'Gratis Beginnen',
    'hero.process': 'Eenvoudig: Prompt → Genereer → Betaal → Geniet',
    
    // Navigation
    'nav.services': 'Diensten',
    'nav.howItWorks': 'Hoe het werkt',
    'nav.songRequest': 'Liedje Aanvraag',
    'nav.voiceCloning': 'Stem Klonen',
    'nav.videoRequest': 'Video Aanvraag',
    'nav.getStarted': 'Start',
    
    // Services
    'services.title': 'Onze Diensten en Prijzen',
    'services.subtitle': 'Begin gratis met creëren! Krijg 3 gratis liedjes, betaal dan per gebruik.',
    'services.freeTier.title': 'Gratis Liedjes Creëren',
    'services.freeTier.description': 'Elke nieuwe gebruiker krijgt 3 GRATIS liedjes om ons AI-platform te ervaren.',
    'services.freeTier.step1': 'Maak je eerste liedje',
    'services.freeTier.step2': 'Verfijn en verbeter',
    'services.freeTier.step3': 'Perfectioneer je creatie',
    
    // Service Details
    'services.songCreation.title': 'Aangepaste Liedjes Maken',
    'services.songCreation.description': 'AI-aangedreven gepersonaliseerde liedjes voor je speciale momenten',
    'services.songCreation.price': 'Gratis',
    'services.songCreation.priceNote': 'Eerste 3 liedjes',
    'services.songCreation.feature1': 'Aangepaste teksten en melodie',
    'services.songCreation.feature2': 'Meerdere genre-opties',
    'services.songCreation.feature3': 'Tot 3 revisies per liedje',
    'services.songCreation.feature4': 'Hoogwaardig audiobestand',
    'services.songCreation.feature5': 'Persoonlijke gebruiksrechten',
    'services.songCreation.feature6': 'Levering binnen 7 dagen',
    
    'services.voiceCloning.title': 'Stem Klonen',
    'services.voiceCloning.description': 'Maak een perfecte replica van je stem voor zingen',
    'services.voiceCloning.price': '250 TL',
    'services.voiceCloning.priceNote': 'per stemkloon',
    'services.voiceCloning.feature1': 'Professionele stemanalyse',
    'services.voiceCloning.feature2': 'Hoogwaardige stemkloon',
    'services.voiceCloning.feature3': 'Meerdere stemvariaties',
    'services.voiceCloning.feature4': 'Trainingsgegevens inbegrepen',
    'services.voiceCloning.feature5': 'API-toegang voor toekomstig gebruik',
    'services.voiceCloning.feature6': 'Levering binnen 14 dagen',
    
    'services.videoAnimation.title': 'Foto/Video Animatie',
    'services.videoAnimation.description': 'Breng je foto\'s tot leven met AI-animatie',
    'services.videoAnimation.price': '500 TL',
    'services.videoAnimation.priceNote': 'per video',
    'services.videoAnimation.feature1': 'AI-aangedreven animatie',
    'services.videoAnimation.feature2': 'Meerdere stijl-opties',
    'services.videoAnimation.feature3': 'Aangepaste videoscenario\'s',
    'services.videoAnimation.feature4': 'Hoge resolutie output',
    'services.videoAnimation.feature5': 'Ondersteuning voor meerdere formaten',
    'services.videoAnimation.feature6': 'Levering binnen 10 dagen',
    
    // Pricing
    'pricing.freeTier.name': 'Gratis Pakket',
    'pricing.freeTier.price': 'Gratis',
    'pricing.freeTier.description': 'Perfect om onze dienst uit te proberen',
    'pricing.freeTier.feature1': '3 gratis liedjes maken',
    'pricing.freeTier.feature2': 'Basis aanpassingsopties',
    'pricing.freeTier.feature3': 'Standaard kwaliteit output',
    'pricing.freeTier.feature4': 'E-mail ondersteuning',
    'pricing.freeTier.feature5': '7-daagse levering',
    'pricing.freeTier.button': 'Gratis Beginnen',
    
    'pricing.payPerUse.name': 'Per Gebruik Betalen',
    'pricing.payPerUse.price': 'Variabel',
    'pricing.payPerUse.description': 'Betaal alleen voor wat je nodig hebt',
    'pricing.payPerUse.feature1': 'Extra liedjes: elk 500 TL',
    'pricing.payPerUse.feature2': 'Stem klonen: elk 250 TL',
    'pricing.payPerUse.feature3': 'Video animatie: elk 500 TL',
    'pricing.payPerUse.feature4': 'Premium kwaliteit output',
    'pricing.payPerUse.feature5': 'Standaard ondersteuning',
    'pricing.payPerUse.feature6': '7-daagse levering',
    'pricing.payPerUse.button': 'Per Gebruik Betalen',
    
    // Payment Information
    'payment.title': 'Betalingsinformatie',
    'payment.description': 'Betaling wordt ontvangen nadat de eerste drie gratis stappen zijn voltooid. We accepteren betalingen in Turkse Lira (TL).',
    'payment.pricing.title': 'Serviceprijzen (TL)',
    'payment.songGeneration': 'Liedjes Genereren: 500 TL',
    'payment.voiceCloning': 'Stem Klonen: 250 TL',
    'payment.videoCreation': 'Video Maken: 500 TL',
    'payment.gateways.title': 'Betaalpoorten',
    'payment.iyzico': 'Veilige Turkse betaalpoort',
    'payment.paytr': 'Alternatieve Turkse betaaloplossing',
    'payment.comingSoon': 'Binnenkort Beschikbaar',
    'payment.accountsOpening': 'Betaalrekeningen worden momenteel geopend',
    
    // How It Works
    'howItWorks.title': 'Hoe Het Werkt',
    'howItWorks.subtitle': 'Maak je aangepaste liedje in slechts 3 eenvoudige stappen',
    'howItWorks.step1.title': 'Maak Je Liedje',
    'howItWorks.step1.description': 'Beschrijf je visie en laat AI je perfecte liedje maken',
    'howItWorks.step1.detail1': 'Beschrijf je speciale moment',
    'howItWorks.step1.detail2': 'Deel je verhaal en emoties',
    'howItWorks.step1.detail3': 'Kies je voorkeursstijl',
    'howItWorks.step2.title': 'Kloon Je Stem',
    'howItWorks.step2.description': 'Upload een voorbeeld en krijg je unieke stemkloon',
    'howItWorks.step2.detail1': 'Upload je stemvoorbeeld',
    'howItWorks.step2.detail2': 'AI-analyse wordt uitgevoerd',
    'howItWorks.step2.detail3': 'Krijg je perfecte stemkloon',
    'howItWorks.step3.title': 'Animeer Je Foto\'s',
    'howItWorks.step3.description': 'Verander statische afbeeldingen in dynamische video\'s',
    'howItWorks.step3.detail1': 'Upload je foto',
    'howItWorks.step3.detail2': 'Kies animatiestijl',
    'howItWorks.step3.detail3': 'Krijg je live video',
    'howItWorks.learnMore': 'Meer Informatie',
    'howItWorks.cta.title': 'Begin Nu',
    'howItWorks.cta.description': 'Klaar om je speciale momenten onvergetelijk te maken?',
    'howItWorks.cta.button': 'Gratis Beginnen met Creëren',
    
    // Footer
    'footer.description': 'We create personalized songs and videos that make your special moments unforgettable. Powered by the latest AI technologies including Suno API, KITS AI, and RunwayML.',
    'footer.location': 'Istanbul, Turkey',
    'footer.copyright': '© 2024 SongCreator. All rights reserved.',
    'footer.categories.services': 'Diensten',
    'footer.categories.company': 'Bedrijf',
    'footer.categories.support': 'Ondersteuning',
    'footer.categories.resources': 'Bronnen',
    'footer.services.songCreation': 'Aangepaste Liedjes Maken',
    'footer.services.voiceCloning': 'Stem Klonen',
    'footer.services.videoAnimation': 'Foto/Video Animatie',


    'footer.company.aboutUs': 'Over Ons',

    'footer.company.contact': 'Contact',
    'footer.support.helpCenter': 'Hulpcentrum',
    'footer.support.termsOfService': 'Gebruiksvoorwaarden',
    'footer.support.privacyPolicy': 'Privacybeleid',


    'footer.resources.examplesGallery': 'Voorbeelden Galerij',
    'footer.resources.pricingCalculator': 'Prijsberekenaar',
    
    // Song Form
    'songForm.title': 'Maak Je Perfecte Liedje',
    'songForm.subtitle': 'Vertel ons over je visie en we maken een gepersonaliseerd liedje dat je emoties perfect vastlegt.',
    'songForm.fields.fullName': 'Volledige Naam',
    'songForm.fields.email': 'E-mail',
    'songForm.fields.phone': 'Telefoonnummer',
    'songForm.fields.specialOccasion': 'Speciale Gelegenheid',
    'songForm.fields.songStyle': 'Liedjestijl',
    'songForm.fields.mood': 'Stemming',
    'songForm.fields.tempo': 'Tempo',
    'songForm.fields.namesToInclude': 'Namen om Op te Nemen',
    'songForm.fields.yourStory': 'Jouw Verhaal',
    'songForm.fields.additionalNotes': 'Aanvullende Notities',
    'songForm.placeholders.fullName': 'Voer je volledige naam in',
    'songForm.placeholders.email': 'your.email@example.com',
    'songForm.placeholders.phone': '+32651544223',
    'songForm.placeholders.selectOccasion': 'Selecteer een gelegenheid',
    'songForm.placeholders.chooseStyle': 'Kies een stijl',
    'songForm.placeholders.selectMood': 'Selecteer de stemming',
    'songForm.placeholders.chooseTempo': 'Kies tempo',
    'songForm.placeholders.namesToInclude': 'bijv. Sarah & John, Mama & Papa',
    'songForm.placeholders.yourStory': 'Vertel ons het verhaal achter dit liedje. Wat maakt het speciaal? Welke emoties wil je vastleggen?',
    'songForm.placeholders.additionalNotes': 'Specifieke teksten, referenties of speciale verzoeken die je wilt opnemen?',
    'songForm.submitButton.submitting': 'Je Liedje Wordt Gemaakt...',
    'songForm.submitButton.createSong': 'Maak Mijn Liedje',
    'songForm.submitButton.reviewTime': 'We bekijken je verzoek en nemen binnen 24 uur contact met je op',
    
    // Voice Form
    'voiceForm.title': 'Kloon Je Stem',
    'voiceForm.subtitle': 'Zing je gevoelens met je eigen gekloonde stem. Upload een voorbeeld en we maken een perfecte replica.',
    'voiceForm.nameLabel': 'Volledige Naam *',
    'voiceForm.emailLabel': 'E-mail *',
    'voiceForm.purposeLabel': 'Doel van Stemklonen *',
    'voiceForm.audioSampleLabel': 'Audio Voorbeeld *',
    'voiceForm.additionalNotesLabel': 'Aanvullende Notities',
    'voiceForm.namePlaceholder': 'Voer je volledige naam in',
    'voiceForm.emailPlaceholder': 'your.email@example.com',
    'voiceForm.selectPurpose': 'Selecteer het doel',
    'voiceForm.uploadAudioPrompt': 'Upload je audio voorbeeld',
    'voiceForm.supportedFormats': 'Ondersteunde formaten: MP3, WAV, M4A (Max 10MB)',
    'voiceForm.chooseAudioFile': 'Kies Audio Bestand',
    'voiceForm.changeFile': 'Wijzig Bestand',
    'voiceForm.removeFile': 'Verwijder',
    'voiceForm.audioNotSupported': 'Je browser ondersteunt het audio element niet.',
    'voiceForm.requirements': 'Vereisten:',
    'voiceForm.requirementsDescription': 'Duidelijke spraak/gezang, minimale achtergrondruis, 30+ seconden aanbevolen',
    'voiceForm.additionalNotesPlaceholder': 'Specifieke vereisten of notities over je stemklonen project...',
    'voiceForm.dataPrivacyTitle': 'Gegevensbescherming en Toestemming',
    'voiceForm.dataPrivacyDescription': 'Door je audio voorbeeld te verstrekken, geef je toestemming voor de verwerking en opslag van je stemgegevens voor het doel van het maken van een stemkloon. Je gegevens worden behandeld in overeenstemming met GDPR-voorschriften en worden alleen gebruikt voor het gespecificeerde doel. Je hebt het recht om op elk moment verwijdering van je gegevens te verzoeken.',
    'voiceForm.gdprConsent': 'Ik geef toestemming voor de verwerking en opslag van mijn stemgegevens voor stemklonen doeleinden, en ik begrijp mijn rechten onder GDPR-voorschriften.',
    'voiceForm.consentAlert': 'Geef alstublieft toestemming voor gegevensopslag en -verwerking.',
    'voiceForm.processingMessage': 'Je Verzoek Wordt Verwerkt...',
    'voiceForm.startVoiceCloning': 'Begin met Stemklonen',
    'voiceForm.responseTime': 'We analyseren je audio en nemen binnen 48 uur contact met je op',
    'voiceForm.purposes.personal': 'Persoonlijke liedjes opname',
    'voiceForm.purposes.podcast': 'Podcast vertelling',
    'voiceForm.purposes.audiobook': 'Audioboek vertelling',
    'voiceForm.purposes.voiceActing': 'Stemacteren',
    'voiceForm.purposes.assistant': 'Persoonlijke assistent stem',
    'voiceForm.purposes.other': 'Anders',
    
    // Photo/Video Form
    'photoVideoForm.bringYourPhotos': 'Breng Je Foto\'s Tot Leven',
    'photoVideoForm.turnYourPhotosIntoMovingVideos': 'Verander je foto\'s in bewegende video\'s en maak indrukwekkende muziekvideo clips met AI-aangedreven animatie.',
    'photoVideoForm.fullName': 'Volledige Naam *',
    'photoVideoForm.email': 'E-mail *',
    'photoVideoForm.photosVideos': 'Foto\'s en Video\'s *',
    'photoVideoForm.animationStyle': 'Animatiestijl',
    'photoVideoForm.desiredDuration': 'Gewenste Duur',
    'photoVideoForm.animationPrompt': 'Animatie Aanwijzing *',
    'photoVideoForm.videoScenario': 'Video Scenario',
    'photoVideoForm.additionalNotes': 'Aanvullende Notities',
    'photoVideoForm.enterYourFullName': 'Voer je volledige naam in',
    'photoVideoForm.yourEmailExample': 'your.email@example.com',
    'photoVideoForm.uploadYourPhotosVideos': 'Upload je foto\'s en video\'s',
    'photoVideoForm.supportedFormats': 'Ondersteunde formaten: JPG, PNG, MP4, MOV (Max 50MB totaal)',
    'photoVideoForm.chooseFiles': 'Kies Bestanden',
    'photoVideoForm.addMoreFiles': 'Voeg Meer Bestanden Toe',
    'photoVideoForm.requirements': 'Vereisten',
    'photoVideoForm.highQualityImagesVideos': 'Hoogwaardige afbeeldingen/video\'s, goede belichting, duidelijke onderwerpen',
    'photoVideoForm.chooseAstyle': 'Kies een stijl',
    'photoVideoForm.selectDuration': 'Selecteer duur',
    'photoVideoForm.describeHowYouWantYourPhotosToMove': 'Beschrijf hoe je wilt dat je foto\'s bewegen en animeren. Wees specifiek over bewegingen, effecten en overgangen...',
    'photoVideoForm.describeTheOverallVideoConcept': 'Beschrijf het algemene videoconcept, verhaal of stemming die je wilt creëren...',
    'photoVideoForm.anySpecificRequirements': 'Specifieke vereisten, referenties of speciale verzoeken voor je video...',
    'photoVideoForm.dataPrivacyConsent': 'Gegevensbescherming en Toestemming',
    'photoVideoForm.consentDescription': 'Door je mediabestanden te uploaden, geef je toestemming voor de verwerking en opslag van je inhoud voor het doel van het maken van geanimeerde video\'s. Je gegevens worden behandeld in overeenstemming met GDPR-voorschriften en worden alleen gebruikt voor het gespecificeerde doel. Je hebt het recht om op elk moment verwijdering van je gegevens te verzoeken.',
    'photoVideoForm.consentCheckboxText': 'Ik geef toestemming voor de verwerking en opslag van mijn mediabestanden voor videomaken doeleinden, en ik begrijp mijn rechten onder GDPR-voorschriften. *',
    'photoVideoForm.consentAlert': 'Geef alstublieft toestemming voor gegevensopslag en -verwerking.',
    'photoVideoForm.processingYourRequest': 'Je Verzoek Wordt Verwerkt...',
    'photoVideoForm.createMyVideo': 'Maak Mijn Video',
    'photoVideoForm.reviewYourRequest': 'We bekijken je verzoek en nemen binnen 48 uur contact met je op',
    'photoVideoForm.styles.cinematic': 'Cinematisch',
    'photoVideoForm.styles.romantic': 'Romantisch',
    'photoVideoForm.styles.adventure': 'Avontuur',
    'photoVideoForm.styles.fantasy': 'Fantasy',
    'photoVideoForm.styles.documentary': 'Documentaire',
    'photoVideoForm.styles.artistic': 'Artistiek',
    'photoVideoForm.styles.modern': 'Modern',
    'photoVideoForm.styles.vintage': 'Vintage',
    'photoVideoForm.styles.minimalist': 'Minimalistisch',
    'photoVideoForm.styles.dynamic': 'Dynamisch',
    'photoVideoForm.durations.short': '15-30 seconden',
    'photoVideoForm.durations.medium': '30-60 seconden',
    'photoVideoForm.durations.long': '1-2 minuten',
    'photoVideoForm.durations.mediumLong': '2-3 minuten',
    'photoVideoForm.durations.longer': '3-5 minuten',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('tr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && translations[savedLanguage as keyof typeof translations]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (newLanguage: string) => {
    if (translations[newLanguage as keyof typeof translations]) {
      setLanguage(newLanguage);
      localStorage.setItem('language', newLanguage);
    }
  };

  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations];
    return langTranslations?.[key as keyof typeof langTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
