'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  changeLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    // Hero Section
    'hero.subtitle': 'Özel anlarınız için kişiselleştirilmiş şarkılar yaratın. Düğünlerden doğum günlerine kadar, her kutlamayı unutulmaz kılın.',
    'hero.button': 'Şarkı Oluştur',
    'hero.process': 'Basit: Prompt → Oluştur → Öde → Keyfet',
    'hero.aiPowered': 'AI Destekli Müzik Yaratımı',
    'hero.trust.fastDelivery': 'Hızlı teslimat',
    'hero.trust.studioQuality': 'Stüdyo kalitesi vokaller',
    'hero.trust.royaltySafe': 'Telif hakkı güvenli',
    'hero.overlay.weddingSpecial': 'Düğün Özel',
    'hero.overlay.perfectForFirstDance': 'İlk dansınız için mükemmel',
    'hero.slide1.title': 'İlk Dansınızı Gerçekten Sizin Yapın',
    'hero.slide1.subtitle': 'Özel anınızın büyüsünü yakalayan kişiselleştirilmiş bir şarkı oluşturun. İlk danslardan düğün tekliflerine kadar, her kutlamayı unutulmaz kılın.',
    'hero.slide2.title': 'Her Doğum Günü Bir Tema Şarkısını Hak Eder',
    'hero.slide2.subtitle': 'Doğum gününüzü hikayenizi anlatan özel bir şarkıyla müzikal bir kutlamaya dönüştürün. Dönüm noktası doğum günleri ve özel kutlamalar için mükemmel.',
    'hero.slide3.title': 'Aşk Hikayenizi Şarkıda Kutlayın',
    'hero.slide3.subtitle': 'Birlikte geçirdiğiniz yolculuğu yakalayan güzel, kişiselleştirilmiş bir şarkıyla yıldönümünüzü işaretleyin. Her yıl kendi melodisini hak eder.',
    'hero.slide4.title': 'Teklifinizi Unutulmaz Yapın',
    'hero.slide4.subtitle': 'Aşk hikayenizi yakalayan özel bir şarkıyla özel anınız için mükemmel ruh halini yaratın. Sonsuza dek sürecek anılar oluşturun.',
    'hero.slide5.title': 'Başarılarınızı Şarkıda Kutlayın',
    'hero.slide5.subtitle': 'Mezuniyetinizi, terfinizi veya herhangi bir dönüm noktasını başarınızı ve yolculuğunuzu kutlayan kişiselleştirilmiş bir marşla işaretleyin.',
    
    // Navigation
    'nav.services': 'Hizmetler',
    'nav.howItWorks': 'Nasıl Çalışır',
    'nav.requestSong': 'Şarkı Talebi',
    'nav.requestVideo': 'Video Talebi',
    'nav.getStarted': 'Başla',
    
    // Services
    'services.title': 'Hizmetlerimiz',
    'services.subtitle': 'Özel anlarınız için kişiselleştirilmiş AI destekli hizmetler sunuyoruz.',
    'services.paymentInfo.title': 'Ödeme Bilgileri',
    'services.paymentInfo.description': 'Prompt gönderdiğinizde ödeme yapılır. Memnun kalmazsanız 2 yeniden oluşturma hakkı dahildir.',
    'services.paymentInfo.step1': 'Prompt gönderin',
    'services.paymentInfo.step2': 'Ödeme yapın',
    'services.paymentInfo.step3': 'Şarkınızı alın',
    
    // Service Details
    'services.songCreation.title': 'Özel Şarkı Oluşturma',
    'services.songCreation.description': 'Özel anlarınız için AI destekli kişiselleştirilmiş şarkılar',
    'services.songCreation.price': '500 TL',
    'services.songCreation.priceNote': 'şarkı başına',
    'services.songCreation.feature1': 'Özel sözler ve melodi',
    'services.songCreation.feature2': 'Çoklu tür seçenekleri',
    'services.songCreation.feature3': 'Şarkı başına 3 revizyon',
    'services.songCreation.feature4': 'Yüksek kaliteli ses dosyası',
    'services.songCreation.feature5': 'Kişisel kullanım hakları',
    'services.songCreation.feature6': '5 dakika içinde teslimat',
    
    'services.voiceCloning.title': 'Ses Klonlama',
    'services.voiceCloning.description': 'Şarkı söylemek için sesinizin mükemmel bir kopyasını oluşturun',
    'services.voiceCloning.price': '250 TL',
    'services.voiceCloning.priceNote': 'ses klonu başına',
    'services.voiceCloning.feature1': 'Profesyonel ses analizi',
    'services.voiceCloning.feature2': 'Yüksek kaliteli ses klonu',
    'services.voiceCloning.feature3': 'Çoklu ses varyasyonları',
    'services.voiceCloning.feature4': 'Eğitim verisi dahil',
    'services.voiceCloning.feature5': 'Gelecekteki kullanım için API erişimi',
    'services.voiceCloning.feature6': '5 dakika içinde teslimat',
    
    'services.videoAnimation.title': 'Fotoğraf/Video Animasyonu',
    'services.videoAnimation.description': 'Fotoğraflarınızı AI animasyonu ile hayata geçirin',
    'services.videoAnimation.price': '500 TL',
    'services.videoAnimation.priceNote': 'video başına',
    'services.videoAnimation.feature1': 'AI destekli animasyon',
    'services.videoAnimation.feature2': 'Çoklu stil seçenekleri',
    'services.videoAnimation.feature3': 'Özel video senaryoları',
    'services.videoAnimation.feature4': 'Yüksek çözünürlüklü çıktı',
    'services.videoAnimation.feature5': 'Çoklu format desteği',
    'services.videoAnimation.feature6': '5 dakika içinde teslimat',
    
    // Pricing
    'pricing.payPerUse.name': 'Kullanım Başına Ödeme',
    'pricing.payPerUse.price': '500 TL',
    'pricing.payPerUse.description': 'Prompt gönderdiğinizde ödeme yapın. 2 yeniden oluşturma hakkı dahildir.',
    'pricing.payPerUse.feature1': 'Şarkı oluşturma: 500 TL',
    'pricing.payPerUse.feature2': 'Ses klonlama: 250 TL',
    'pricing.payPerUse.feature3': 'Video animasyonu: 500 TL',
    'pricing.payPerUse.feature4': 'Premium kalite çıktısı',
    'pricing.payPerUse.feature5': '2 yeniden oluşturma hakkı',
    'pricing.payPerUse.button': 'Şarkı Oluşturmaya Başla',
    
    // Payment Information
    'payment.title': 'Ödeme Bilgileri',
    'payment.description': 'Prompt gönderdiğinizde ödeme yapılır. Memnun kalmazsanız 2 yeniden oluşturma hakkı dahildir. Türk Lirası (TL) ile ödeme kabul ediyoruz.',
    'payment.pricing.title': 'Hizmet Fiyatlandırması (TL)',
    'payment.songGeneration': 'Şarkı Oluşturma: 500 TL',
    'payment.voiceCloning': 'Ses Klonlama: 250 TL',
    'payment.videoCreation': 'Video Oluşturma: 500 TL',
    'payment.gateways.title': 'Ödeme Geçitleri',
    'payment.iyzico': 'Güvenli Türk ödeme geçidi',
    'payment.paytr': 'Alternatif Türk ödeme çözümü',
    'payment.comingSoon': 'Yakında',
    'payment.accountsOpening': 'Ödeme hesapları şu anda açılıyor',
    
    // How It Works
    'howItWorks.title': 'Nasıl Çalışır',
    'howItWorks.subtitle': '3 Basit Adımda',
    'howItWorks.description': 'Fikirden bitmiş şarkıya dakikalar içinde. AI destekli platformumuz kişiselleştirilmiş müzik oluşturmayı vizyonunuzu tanımlamak kadar kolay hale getirir.',
    'howItWorks.step1.title': 'Vizyonunuzu Tanımlayın',
    'howItWorks.step1.description': 'Özel anınızı, istediğiniz ruh halini ve sizin için önemli olan herhangi bir detayı anlatın.',
    'howItWorks.step2.title': 'AI Şarkınızı Yaratır',
    'howItWorks.step2.description': 'Gelişmiş AI\'mız vizyonunuzu analiz eder ve sadece sizin için benzersiz, kişiselleştirilmiş bir şarkı besteler.',
    'howItWorks.step3.title': 'İnceleyin ve Mükemmelleştirin',
    'howItWorks.step3.description': 'Şarkınızı dinleyin ve gerekirse yeniden oluşturun. 3 deneme sistemimizle tam olarak doğru olmasını sağlayın.',
    'howItWorks.learnMore': 'Daha Fazla Bilgi',
    'howItWorks.cta.title': 'Hemen Başlayın',
    'howItWorks.cta.description': 'Özel anlarınızı unutulmaz kılmaya hazır mısınız?',
    'howItWorks.cta.button': 'Şarkı Oluşturmaya Başla',
    
    // Footer
    'footer.description': 'Özel anlarınız için kişiselleştirilmiş şarkılar oluşturun. AI destekli platformumuzla düğünlerden doğum günlerine kadar her kutlamayı unutulmaz kılın.',
    'footer.features.aiMusic': 'AI Müzik',
    'footer.features.multiLanguage': 'Çok Dilli',
    'footer.features.fastDelivery': 'Hızlı Teslimat',
    'footer.quickLinks.title': 'Hızlı Bağlantılar',
    'footer.quickLinks.howItWorks': 'Nasıl Çalışır',
    'footer.quickLinks.createSong': 'Şarkı Oluştur',
    'footer.quickLinks.aboutUs': 'Hakkımızda',
    'footer.quickLinks.contact': 'İletişim',
    'footer.contact.title': 'İletişim',
    'footer.privacyPolicy': 'Gizlilik Politikası',
    'footer.termsOfService': 'Kullanım Şartları',
    'footer.poweredBy.text': 'Destekleyen',
    'footer.poweredBy.aiTechnology': 'AI Teknolojisi',
    'footer.location': 'İstanbul, Türkiye',
    'footer.copyright': '© 2024 SongCreator. Tüm hakları saklıdır.',
    'footer.categories.services': 'Hizmetler',
    'footer.categories.company': 'Şirket',
    'footer.categories.support': 'Destek',
    'footer.categories.resources': 'Kaynaklar',
    'footer.services.songCreation': 'Özel Şarkı Oluşturma',
    'footer.services.voiceCloning': 'Ses Klonlama',
    'footer.services.videoAnimation': 'Fotoğraf/Video Animasyonu',

    'footer.company.aboutUs': 'Hakkımızda',

    'footer.company.contact': 'İletişim',
    'footer.support.helpCenter': 'Yardım Merkezi',
    'footer.support.termsOfService': 'Kullanım Şartları',
    'footer.support.privacyPolicy': 'Gizlilik Politikası',


    'footer.resources.examplesGallery': 'Örnekler Galerisi',
    'footer.resources.pricingCalculator': 'Fiyat Hesaplayıcısı',
    
    // Song Form
    'songForm.title': 'Mükemmel Şarkınızı Oluşturun',
    'songForm.subtitle': 'Vizyonunuzu anlatın, duygularınızı mükemmel şekilde yakalayan kişiselleştirilmiş bir şarkı oluşturalım.',
    'songForm.header.title': 'Şarkı Oluşturmaya Başlayın',
    'songForm.header.subtitle': 'Başlamak için aşağıdaki formu doldurun',
    'songForm.fields.fullName': 'Ad Soyad *',
    'songForm.fields.email': 'E-posta *',
    'songForm.fields.songDescription': 'Şarkı Açıklaması *',
    'songForm.fields.occasion': 'Gelegenheid *',
    'songForm.fields.musicalStyle': 'Müzik Stili *',
    'songForm.fields.mood': 'Ruh Hali ve Duygu *',
    'songForm.fields.tempo': 'Tempo *',
    'songForm.fields.language': 'Dil *',
    'songForm.fields.songLength': 'Şarkı Uzunluğu *',
    'songForm.fields.specialInstructions': 'Özel Talimatlar',
    'songForm.fields.referenceSongs': 'Referans Şarkılar (İsteğe Bağlı)',
    'songForm.placeholders.fullName': 'Adınızı ve soyadınızı girin',
    'songForm.placeholders.email': 'your.email@example.com',
    'songForm.placeholders.songDescription': 'Özel anınızı, iletmek istediğiniz duyguları, şarkıda olması gereken belirli bir hikaye veya mesajı anlatın...',
    'songForm.placeholders.specialInstructions': 'İstediğiniz belirli enstrümanlar, vokal stili veya özel elementler var mı? (örn. "Piyano solo ekle", "Kadın vokal", "Yaylı çalgılar ekle", "Dans edilebilir yap")',
    'songForm.placeholders.referenceSongs': 'örn. "Ed Sheeran\'ın Perfect\'i gibi", "Adele\'in tarzına benzer"',
    'songForm.helpText.songDescription': 'Mümkün olduğunca detaylı olun! Şarkıda istediğiniz belirli duyguları, anıları veya hikayeleri dahil edin.',
    'songForm.helpText.specialInstructions': 'İsteğe bağlı: Belirli müzik elementleri, enstrümanlar veya vokal tercihleri ekleyin.',
    'songForm.helpText.referenceSongs': 'Referans için beğendiğiniz şarkıları veya sanatçıları belirtin (isteğe bağlı).',
    'songForm.submitButton': 'Şarkı Talebini Gönder',
    'songForm.responseTime': 'Detaylı talebinizi inceleyeceğiz ve 24 saat içinde size geri döneceğiz',
    
    // Voice Form
    'voiceForm.title': 'Sesinizi Klonlayın',
    'voiceForm.subtitle': 'Kendi klonlanmış sesinizle duygularınızı söyleyin. Bir örnek yükleyin ve mükemmel bir kopya oluşturalım.',
    'voiceForm.nameLabel': 'Ad Soyad *',
    'voiceForm.emailLabel': 'E-posta *',
    'voiceForm.purposeLabel': 'Ses Klonlama Amacı *',
    'voiceForm.audioSampleLabel': 'Ses Örneği *',
    'voiceForm.additionalNotesLabel': 'Ek Notlar',
    'voiceForm.namePlaceholder': 'Adınızı ve soyadınızı girin',
    'voiceForm.emailPlaceholder': 'your.email@example.com',
    'voiceForm.selectPurpose': 'Amacı seçin',
    'voiceForm.uploadAudioPrompt': 'Ses örneğinizi yükleyin',
    'voiceForm.supportedFormats': 'Desteklenen formatlar: MP3, WAV, M4A (Maksimum 10MB)',
    'voiceForm.chooseAudioFile': 'Ses Dosyası Seç',
    'voiceForm.changeFile': 'Dosyayı Değiştir',
    'voiceForm.removeFile': 'Kaldır',
    'voiceForm.audioNotSupported': 'Tarayıcınız ses öğesini desteklemiyor.',
    'voiceForm.requirements': 'Gereksinimler:',
    'voiceForm.requirementsDescription': 'Net konuşma/şarkı, minimal arka plan gürültüsü, 30+ saniye önerilir',
    'voiceForm.additionalNotesPlaceholder': 'Ses klonlama projeniz hakkında özel gereksinimler veya notlar...',
    'voiceForm.dataPrivacyTitle': 'Veri Gizliliği ve Onay',
    'voiceForm.dataPrivacyDescription': 'Ses örneğinizi sağlayarak, ses verilerinizin işlenmesi ve saklanmasına, ses klonu oluşturma amacıyla onay veriyorsunuz. Verileriniz GDPR düzenlemelerine uygun olarak işlenecek ve yalnızca belirtilen amaç için kullanılacaktır. Verilerinizin silinmesini isteme hakkına sahipsiniz.',
    'voiceForm.gdprConsent': 'Ses klonlama amaçları için ses verilerimin işlenmesine ve saklanmasına onay veriyorum ve GDPR düzenlemeleri kapsamındaki haklarımı anlıyorum.',
    'voiceForm.consentAlert': 'Lütfen veri saklama ve işleme için onay verin.',
    'voiceForm.processingMessage': 'Talebiniz İşleniyor...',
    'voiceForm.startVoiceCloning': 'Ses Klonlamaya Başla',
    'voiceForm.responseTime': 'Ses örneğinizi analiz edeceğiz ve 48 saat içinde size geri döneceğiz',
    'voiceForm.purposes.personal': 'Kişisel şarkı kaydı',
    'voiceForm.purposes.podcast': 'Podcast anlatımı',
    'voiceForm.purposes.audiobook': 'Sesli kitap anlatımı',
    'voiceForm.purposes.voiceActing': 'Seslendirme',
    'voiceForm.purposes.assistant': 'Kişisel asistan sesi',
    'voiceForm.purposes.other': 'Diğer',
    
    // Photo/Video Form
    'photoVideoForm.bringYourPhotos': 'Fotoğraflarınızı Canlandırın',
    'photoVideoForm.turnYourPhotosIntoMovingVideos': 'Fotoğraflarınızı hareketli videolara dönüştürün ve AI destekli animasyonla etkileyici müzik video klipleri oluşturun.',
    'photoVideoForm.fullName': 'Ad Soyad *',
    'photoVideoForm.email': 'E-posta *',
    'photoVideoForm.photosVideos': 'Fotoğraflar ve Videolar *',
    'photoVideoForm.animationStyle': 'Animasyon Stili',
    'photoVideoForm.desiredDuration': 'İstenen Süre',
    'photoVideoForm.animationPrompt': 'Animasyon İsteği *',
    'photoVideoForm.videoScenario': 'Video Senaryosu',
    'photoVideoForm.additionalNotes': 'Ek Notlar',
    'photoVideoForm.enterYourFullName': 'Adınızı ve soyadınızı girin',
    'photoVideoForm.yourEmailExample': 'your.email@example.com',
    'photoVideoForm.uploadYourPhotosVideos': 'Fotoğraf ve videolarınızı yükleyin',
    'photoVideoForm.supportedFormats': 'Desteklenen formatlar: JPG, PNG, MP4, MOV (Toplam maksimum 50MB)',
    'photoVideoForm.chooseFiles': 'Dosya Seç',
    'photoVideoForm.addMoreFiles': 'Daha Fazla Dosya Ekle',
    'photoVideoForm.requirements': 'Gereksinimler',
    'photoVideoForm.highQualityImagesVideos': 'Yüksek kaliteli görüntüler/videolar, iyi aydınlatma, net konular',
    'photoVideoForm.chooseAstyle': 'Bir stil seçin',
    'photoVideoForm.selectDuration': 'Süre seçin',
    'photoVideoForm.describeHowYouWantYourPhotosToMove': 'Fotoğraflarınızın nasıl hareket etmesini ve canlanmasını istediğinizi açıklayın. Hareketler, efektler ve geçişler hakkında spesifik olun...',
    'photoVideoForm.describeTheOverallVideoConcept': 'Oluşturmak istediğiniz genel video konseptini, hikayeyi veya ruh halini açıklayın...',
    'photoVideoForm.anySpecificRequirements': 'Videonuz için özel gereksinimler, referanslar veya özel istekler...',
    'photoVideoForm.dataPrivacyConsent': 'Veri Gizliliği ve Onay',
    'photoVideoForm.consentDescription': 'Medya dosyalarınızı yükleyerek, animasyonlu video oluşturma amacıyla içeriğinizin işlenmesine ve saklanmasına onay veriyorsunuz. Verileriniz GDPR düzenlemelerine uygun olarak işlenecek ve yalnızca belirtilen amaç için kullanılacaktır. Verilerinizin silinmesini isteme hakkına sahipsiniz.',
    'photoVideoForm.consentCheckboxText': 'Video oluşturma amaçları için medya dosyalarımın işlenmesine ve saklanmasına onay veriyorum ve GDPR düzenlemeleri kapsamındaki haklarımı anlıyorum. *',
    'photoVideoForm.consentAlert': 'Lütfen veri saklama ve işleme için onay verin.',
    'photoVideoForm.processingYourRequest': 'Talebiniz İşleniyor...',
    'photoVideoForm.createMyVideo': 'Videomu Oluştur',
    'photoVideoForm.reviewYourRequest': 'Talebinizi inceleyeceğiz ve 48 saat içinde size geri döneceğiz',
    'photoVideoForm.styles.cinematic': 'Sinematik',
    'photoVideoForm.styles.romantic': 'Romantik',
    'photoVideoForm.styles.adventure': 'Macera',
    'photoVideoForm.styles.fantasy': 'Fantastik',
    'photoVideoForm.styles.documentary': 'Belgesel',
    'photoVideoForm.styles.artistic': 'Sanatsal',
    'photoVideoForm.styles.modern': 'Modern',
    'photoVideoForm.styles.vintage': 'Vintage',
    'photoVideoForm.styles.minimalist': 'Minimalist',
    'photoVideoForm.styles.dynamic': 'Dinamik',
    'photoVideoForm.durations.short': '15-30 saniye',
    'photoVideoForm.durations.medium': '30-60 saniye',
    'photoVideoForm.durations.long': '1-2 dakika',
    'photoVideoForm.durations.mediumLong': '2-3 dakika',
    'photoVideoForm.durations.longer': '3-5 dakika',
    
    // Video Request Section
    'videoRequest.title': 'AI Sihri ile Kişiselleştirilmiş Videolar Oluşturun',
    'videoRequest.subtitle': 'Fotoğraflarınızı AI üretimi müzik, efektler ve animasyonlarla etkileyici videolara dönüştürün. Sosyal medya, sunumlar ve özel anılar için mükemmel.',
    'videoRequest.features.photoToVideo.title': 'Fotoğraftan Videoya',
    'videoRequest.features.photoToVideo.description': 'Fotoğraflarınızı pürüzsüz geçişler ve efektlerle etkileyici videolara dönüştürün.',
    'videoRequest.features.photoToVideo.feature1': 'AI üretimi geçişler',
    'videoRequest.features.photoToVideo.feature2': 'Özel müzik overlay',
    'videoRequest.features.photoToVideo.feature3': 'Profesyonel efektler',
    'videoRequest.features.musicIntegration.title': 'Müzik Entegrasyonu',
    'videoRequest.features.musicIntegration.description': 'Video içeriğiniz ve ruh halinizle mükemmel şekilde eşleşen kişiselleştirilmiş müzik ekleyin.',
    'videoRequest.features.musicIntegration.feature1': 'Özel şarkı oluşturma',
    'videoRequest.features.musicIntegration.feature2': 'Ruh haline dayalı seçim',
    'videoRequest.features.musicIntegration.feature3': 'Mükemmel zamanlama senkronizasyonu',
    'videoRequest.features.aiEffects.title': 'AI Efektleri',
    'videoRequest.features.aiEffects.description': 'Videolarınızı AI destekli efektler, filtreler ve animasyonlarla geliştirin.',
    'videoRequest.features.aiEffects.feature1': 'Akıllı filtreler',
    'videoRequest.features.aiEffects.feature2': 'Hareket efektleri',
    'videoRequest.features.aiEffects.feature3': 'Stil transferi',
    'videoRequest.cta.button': 'Video Oluşturmaya Başla',

    // Voice Cloning Section
    'voiceCloning.title': 'AI Teknolojisi ile Sesinizi Klonlayın',
    'voiceCloning.subtitle': 'Şarkılar, videolar, podcast\'ler ve daha fazlası için sesinizin dijital kopyasını oluşturun. Gelişmiş AI\'mız sesinizin benzersiz özelliklerini mükemmel şekilde yakalar.',
    'voiceCloning.features.recording.title': 'Ses Kaydı',
    'voiceCloning.features.recording.description': 'Yüksek kaliteli bir ses modeli oluşturmak için sesinizi birkaç dakika kaydedin.',
    'voiceCloning.features.recording.details': 'Sessiz bir ortamda 3-5 dakika net konuşma öneriyoruz',
    'voiceCloning.features.processing.title': 'AI İşleme',
    'voiceCloning.features.processing.description': 'AI\'mız ses kalıplarınızı analiz eder ve dijital ses klonunuzu oluşturur.',
    'voiceCloning.features.processing.details': 'Gelişmiş sinir ağları ton, perde ve benzersiz özellikleri yakalar',
    'voiceCloning.features.integration.title': 'Ses Entegrasyonu',
    'voiceCloning.features.integration.description': 'Klonlanmış sesinizi şarkılarda, videolarda ve diğer yaratıcı projelerde kullanın.',
    'voiceCloning.features.integration.details': 'Kişiselleştirilmiş içerik, sunumlar ve eğlence için mükemmel',
    'voiceCloning.cta.title': 'Ses Klonlamaya Başlayın',
    'voiceCloning.cta.description': 'Sesinizi kaydedin ve AI\'nın dijital ses ikizinizi oluşturmasına izin verin',
    'voiceCloning.cta.button': 'Kayıt Yapmaya Başla',
  },
  en: {
    // Hero Section
    'hero.subtitle': 'Create personalized songs for your special moments. From weddings to birthdays, make every celebration unforgettable with your own unique soundtrack.',
    'hero.button': 'Create Song',
    'hero.process': 'It\'s simple: Prompt → Generate → Pay → Enjoy',
    'hero.aiPowered': 'AI-Powered Music Creation',
    'hero.trust.fastDelivery': 'Fast Delivery',
    'hero.trust.studioQuality': 'Studio quality vocalists',
    'hero.trust.royaltySafe': 'Royalty-safe',
    'hero.overlay.weddingSpecial': 'Wedding Special',
    'hero.overlay.perfectForFirstDance': 'Perfect for your first dance',
    'hero.slide1.title': 'Make Your First Dance Truly Yours',
    'hero.slide1.subtitle': 'Create a personalized song that captures the essence of your special moment. From first dances to wedding proposals, make every celebration unforgettable.',
    'hero.slide2.title': 'Every Birthday Deserves a Theme Song',
    'hero.slide2.subtitle': 'Transform your birthday into a musical celebration with a personalized song that tells your story. Perfect for birthday milestones and special occasions.',
    'hero.slide3.title': 'Celebrate Your Love Story in Song',
    'hero.slide3.subtitle': 'Mark your journey together with a beautiful, personalized song. Each year deserves its own melody.',
    'hero.slide4.title': 'Make Your Proposal Unforgettable',
    'hero.slide4.subtitle': 'Create a perfect mood for your love story with a personalized song. Make it last forever with unforgettable memories.',
    'hero.slide5.title': 'Celebrate Your Success in Song',
    'hero.slide5.subtitle': 'Mark your graduation, graduation, or any milestone with a personalized march that celebrates your success and your journey.',
    
    // Navigation
    'nav.services': 'Services',
    'nav.howItWorks': 'How It Works',
    'nav.requestSong': 'Song Request',
    'nav.requestVideo': 'Video Request',
    'nav.getStarted': 'Get Started',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'We offer personalized AI-powered services for your special moments.',
    'services.paymentInfo.title': 'Payment Information',
    'services.paymentInfo.description': 'Payment happens when you submit your prompt. Includes up to 2 re-generations if you\'re not satisfied.',
    'services.paymentInfo.step1': 'Submit your prompt',
    'services.paymentInfo.step2': 'Make payment',
    'services.paymentInfo.step3': 'Get your song',
    
    // Service Details
    'services.songCreation.title': 'Custom Song Creation',
    'services.songCreation.description': 'AI-powered personalized songs for your special moments',
    'services.songCreation.price': '500 TL',
    'services.songCreation.priceNote': 'per song',
    'services.songCreation.feature1': 'Custom lyrics and melody',
    'services.songCreation.feature2': 'Multiple genre options',
    'services.songCreation.feature3': 'Up to 3 revisions per song',
    'services.songCreation.feature4': 'High-quality audio file',
    'services.songCreation.feature5': 'Personal usage rights',
    'services.songCreation.feature6': 'Delivery up to 5 minutes',
    
    'services.voiceCloning.title': 'Voice Cloning',
    'services.voiceCloning.description': 'Create a perfect replica of your voice for singing',
    'services.voiceCloning.price': '250 TL',
    'services.voiceCloning.priceNote': 'per voice clone',
    'services.voiceCloning.feature1': 'Professional voice analysis',
    'services.voiceCloning.feature2': 'High-fidelity voice clone',
    'services.voiceCloning.feature3': 'Multiple voice variations',
    'services.voiceCloning.feature4': 'Training data included',
    'services.voiceCloning.feature5': 'API access for future use',
    'services.voiceCloning.feature6': 'Delivery up to 5 minutes',
    
    'services.videoAnimation.title': 'Photo/Video Animation',
    'services.videoAnimation.description': 'Bring your photos to life with AI animation',
    'services.videoAnimation.price': '500 TL',
    'services.videoAnimation.priceNote': 'per video',
    'services.videoAnimation.feature1': 'AI-powered animation',
    'services.videoAnimation.feature2': 'Multiple style options',
    'services.videoAnimation.feature3': 'Custom video scenarios',
    'services.videoAnimation.feature4': 'High-resolution output',
    'services.videoAnimation.feature5': 'Multiple format support',
    'services.videoAnimation.feature6': 'Delivery up to 5 minutes',
    
    // Pricing
    'pricing.payPerUse.name': 'Pay Per Use',
    'pricing.payPerUse.price': '500 TL',
    'pricing.payPerUse.description': 'Payment happens when you submit your prompt. Includes up to 2 re-generations if you\'re not satisfied.',
    'pricing.payPerUse.feature1': 'Song creation: 500 TL',
    'pricing.payPerUse.feature2': 'Voice cloning: 250 TL',
    'pricing.payPerUse.feature3': 'Video animation: 500 TL',
    'pricing.payPerUse.feature4': 'Premium quality output',
    'pricing.payPerUse.feature5': '2 re-generation rights',
    'pricing.payPerUse.button': 'Start Creating Song',
    
    // Payment Information
    'payment.title': 'Payment Information',
    'payment.description': 'Payment happens when you submit your prompt. Includes up to 2 re-generations if you\'re not satisfied. We accept payments in Turkish Lira (TL).',
    'payment.pricing.title': 'Service Pricing (TL)',
    'payment.songGeneration': 'Song Generation: 500 TL',
    'payment.voiceCloning': 'Voice Cloning: 250 TL',
    'payment.videoCreation': 'Video Creation: 500 TL',
    'payment.gateways.title': 'Payment Gateways',
    'payment.iyzico': 'Secure Turkish payment gateway',
    'payment.paytr': 'Alternative Turkish payment solution',
    'payment.comingSoon': 'Coming Soon',
    'payment.accountsOpening': 'Payment accounts are currently being opened',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': '3 Simple Steps',
    'howItWorks.description': 'From idea to finished song in minutes. Our AI-powered platform makes creating personalized music as easy as describing your vision.',
    'howItWorks.step1.title': 'Describe Your Vision',
    'howItWorks.step1.description': 'Tell us about your special moment, the mood you want, and any specific details that matter to you.',
    'howItWorks.step2.title': 'AI Creates Your Song',
    'howItWorks.step2.description': 'Our advanced AI analyzes your vision and composes a unique, personalized song just for you.',
    'howItWorks.step3.title': 'Review & Perfect',
    'howItWorks.step3.description': 'Listen to your song and regenerate if needed. Get it exactly right with our 3-try system.',
    'howItWorks.learnMore': 'Learn More',
    'howItWorks.cta.title': 'Get Started Now',
    'howItWorks.cta.description': 'Ready to make your special moments unforgettable?',
    'howItWorks.cta.button': 'Start Creating Song',
    
    // Footer
    'footer.description': 'We create personalized songs and videos that make your special moments unforgettable. Powered by the latest AI technologies including Suno API, KITS AI, and RunwayML.',
    'footer.features.aiMusic': 'AI Music',
    'footer.features.multiLanguage': 'Multi-Language',
    'footer.features.fastDelivery': 'Fast Delivery',
    'footer.quickLinks.title': 'Quick Links',
    'footer.quickLinks.howItWorks': 'How It Works',
    'footer.quickLinks.createSong': 'Create Song',
    'footer.quickLinks.aboutUs': 'About Us',
    'footer.quickLinks.contact': 'Contact',
    'footer.contact.title': 'Contact',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.poweredBy.text': 'Powered by',
    'footer.poweredBy.aiTechnology': 'AI Technology',
    'footer.location': 'Istanbul, Turkey',
    'footer.copyright': '© 2024 SongCreator. All rights reserved.',
    'footer.categories.services': 'Services',
    'footer.categories.company': 'Company',
    'footer.categories.support': 'Support',
    'footer.categories.resources': 'Resources',
    'footer.services.songCreation': 'Custom Song Creation',
    'footer.services.voiceCloning': 'Voice Cloning',
    'footer.services.videoAnimation': 'Photo/Video Animation',

    'footer.company.aboutUs': 'About Us',

    'footer.company.contact': 'Contact',
    'footer.support.helpCenter': 'Help Center',
    'footer.support.termsOfService': 'Terms of Service',
    'footer.support.privacyPolicy': 'Privacy Policy',


    'footer.resources.examplesGallery': 'Examples Gallery',
    'footer.resources.pricingCalculator': 'Pricing Calculator',
    
    // Song Form
    'songForm.title': 'Create Your Perfect Song',
    'songForm.subtitle': 'Tell us about your vision and we\'ll create a personalized song that captures your emotions perfectly.',
    'songForm.header.title': 'Start Creating Song',
    'songForm.header.subtitle': 'Fill out the form below to get started',
    'songForm.fields.fullName': 'Full Name *',
    'songForm.fields.email': 'Email *',
    'songForm.fields.songDescription': 'Song Description *',
    'songForm.fields.occasion': 'Occasion *',
    'songForm.fields.musicalStyle': 'Musical Style *',
    'songForm.fields.mood': 'Mood and Emotion *',
    'songForm.fields.tempo': 'Tempo *',
    'songForm.fields.language': 'Language *',
    'songForm.fields.songLength': 'Song Length *',
    'songForm.fields.specialInstructions': 'Special Instructions',
    'songForm.fields.referenceSongs': 'Reference Songs (Optional)',
    'songForm.placeholders.fullName': 'Enter your full name',
    'songForm.placeholders.email': 'your.email@example.com',
    'songForm.placeholders.songDescription': 'Tell us about your special moment, the emotions you want to express, and the specific story or message you want in the song...',
    'songForm.placeholders.specialInstructions': 'Do you want to include any specific instruments, vocal style, or elements? (e.g., "Add piano solo", "Female vocals", "Add string instruments", "Dancable arrangement")',
    'songForm.placeholders.referenceSongs': 'e.g., "Like Ed Sheeran\'s Perfect", "Similar to Adele\'s style"',
    'songForm.helpText.songDescription': 'Be as detailed as possible! Include the specific emotions, memories, or stories you want in the song.',
    'songForm.helpText.specialInstructions': 'Optional: Add any specific music elements, instruments, or vocal preferences.',
    'songForm.helpText.referenceSongs': 'Please mention any songs or artists you like for reference (optional).',
    'songForm.submitButton': 'Submit Song Request',
    'songForm.responseTime': 'We\'ll review your request and get back to you within 24 hours',
    
    // Voice Form
    'voiceForm.title': 'Clone Your Voice',
    'voiceForm.subtitle': 'Sing your feelings with your own cloned voice. Upload a sample and we\'ll create a perfect replica.',
    'voiceForm.nameLabel': 'Full Name *',
    'voiceForm.emailLabel': 'Email *',
    'voiceForm.purposeLabel': 'Purpose of Voice Cloning *',
    'voiceForm.audioSampleLabel': 'Audio Sample *',
    'voiceForm.additionalNotesLabel': 'Additional Notes',
    'voiceForm.namePlaceholder': 'Enter your full name',
    'voiceForm.emailPlaceholder': 'your.email@example.com',
    'voiceForm.selectPurpose': 'Select the purpose',
    'voiceForm.uploadAudioPrompt': 'Upload your audio sample',
    'voiceForm.supportedFormats': 'Supported formats: MP3, WAV, M4A (Max 10MB)',
    'voiceForm.chooseAudioFile': 'Choose Audio File',
    'voiceForm.changeFile': 'Change File',
    'voiceForm.removeFile': 'Remove',
    'voiceForm.audioNotSupported': 'Your browser does not support the audio element.',
    'voiceForm.requirements': 'Requirements:',
    'voiceForm.requirementsDescription': 'Clear speech/singing, minimal background noise, 30+ seconds recommended',
    'voiceForm.additionalNotesPlaceholder': 'Any specific requirements or notes about your voice cloning project...',
    'voiceForm.dataPrivacyTitle': 'Data Privacy & Consent',
    'voiceForm.dataPrivacyDescription': 'By providing your audio sample, you consent to the processing and storage of your voice data for the purpose of creating a voice clone. Your data will be handled in accordance with GDPR regulations and will only be used for the specified purpose. You have the right to request deletion of your data at any time.',
    'voiceForm.gdprConsent': 'I consent to the processing and storage of my voice data for voice cloning purposes, and I understand my rights under GDPR regulations.',
    'voiceForm.consentAlert': 'Please provide consent for data storage and processing.',
    'voiceForm.processingMessage': 'Processing Your Request...',
    'voiceForm.startVoiceCloning': 'Start Voice Cloning',
    'voiceForm.responseTime': 'We\'ll analyze your audio and get back to you within 48 hours',
    'voiceForm.purposes.personal': 'Personal song recording',
    'voiceForm.purposes.podcast': 'Podcast narration',
    'voiceForm.purposes.audiobook': 'Audiobook narration',
    'voiceForm.purposes.voiceActing': 'Voice acting',
    'voiceForm.purposes.assistant': 'Personal assistant voice',
    'voiceForm.purposes.other': 'Other',
    
    // Photo/Video Form
    'photoVideoForm.bringYourPhotos': 'Bring Your Photos to Life',
    'photoVideoForm.turnYourPhotosIntoMovingVideos': 'Turn your photos into moving videos and create stunning music video clips with AI-powered animation.',
    'photoVideoForm.fullName': 'Full Name *',
    'photoVideoForm.email': 'Email *',
    'photoVideoForm.photosVideos': 'Photos & Videos *',
    'photoVideoForm.animationStyle': 'Animation Style',
    'photoVideoForm.desiredDuration': 'Desired Duration',
    'photoVideoForm.animationPrompt': 'Animation Prompt *',
    'photoVideoForm.videoScenario': 'Video Scenario',
    'photoVideoForm.additionalNotes': 'Additional Notes',
    'photoVideoForm.enterYourFullName': 'Enter your full name',
    'photoVideoForm.yourEmailExample': 'your.email@example.com',
    'photoVideoForm.uploadYourPhotosVideos': 'Upload your photos and videos',
    'photoVideoForm.supportedFormats': 'Supported formats: JPG, PNG, MP4, MOV (Max 50MB total)',
    'photoVideoForm.chooseFiles': 'Choose Files',
    'photoVideoForm.addMoreFiles': 'Add More Files',
    'photoVideoForm.requirements': 'Requirements',
    'photoVideoForm.highQualityImagesVideos': 'High quality images/videos, good lighting, clear subjects',
    'photoVideoForm.chooseAstyle': 'Choose a style',
    'photoVideoForm.selectDuration': 'Select duration',
    'photoVideoForm.describeHowYouWantYourPhotosToMove': 'Describe how you want your photos to move and animate. Be specific about movements, effects, and transitions...',
    'photoVideoForm.describeTheOverallVideoConcept': 'Describe the overall video concept, story, or mood you want to create...',
    'photoVideoForm.anySpecificRequirements': 'Any specific requirements, references, or special requests for your video...',
    'photoVideoForm.dataPrivacyConsent': 'Data Privacy & Consent',
    'photoVideoForm.consentDescription': 'By uploading your media files, you consent to the processing and storage of your content for the purpose of creating animated videos. Your data will be handled in accordance with GDPR regulations and will only be used for the specified purpose. You have the right to request deletion of your data at any time.',
    'photoVideoForm.consentCheckboxText': 'I consent to the processing and storage of my media files for video creation purposes, and I understand my rights under GDPR regulations. *',
    'photoVideoForm.consentAlert': 'Please provide consent for data storage and processing.',
    'photoVideoForm.processingYourRequest': 'Processing Your Request...',
    'photoVideoForm.createMyVideo': 'Create My Video',
    'photoVideoForm.reviewYourRequest': 'We\'ll review your request and get back to you within 48 hours',
    'photoVideoForm.styles.cinematic': 'Cinematic',
    'photoVideoForm.styles.romantic': 'Romantic',
    'photoVideoForm.styles.adventure': 'Adventure',
    'photoVideoForm.styles.fantasy': 'Fantasy',
    'photoVideoForm.styles.documentary': 'Documentary',
    'photoVideoForm.styles.artistic': 'Artistic',
    'photoVideoForm.styles.modern': 'Modern',
    'photoVideoForm.styles.vintage': 'Vintage',
    'photoVideoForm.styles.minimalist': 'Minimalist',
    'photoVideoForm.styles.dynamic': 'Dynamic',
    'photoVideoForm.durations.short': '15-30 seconds',
    'photoVideoForm.durations.medium': '30-60 seconds',
    'photoVideoForm.durations.long': '1-2 minutes',
    'photoVideoForm.durations.mediumLong': '2-3 minutes',
    'photoVideoForm.durations.longer': '3-5 minutes',
    
    // Video Request Section
    'videoRequest.title': 'Create Personalized Videos with AI Magic',
    'videoRequest.subtitle': 'Transform your photos into stunning videos with AI-generated music, effects, and animations. Perfect for social media, presentations, and special memories.',
    'videoRequest.features.photoToVideo.title': 'Photo to Video',
    'videoRequest.features.photoToVideo.description': 'Convert your photos into engaging videos with smooth transitions and effects.',
    'videoRequest.features.photoToVideo.feature1': 'AI-generated transitions',
    'videoRequest.features.photoToVideo.feature2': 'Custom music overlay',
    'videoRequest.features.photoToVideo.feature3': 'Professional effects',
    'videoRequest.features.musicIntegration.title': 'Music Integration',
    'videoRequest.features.musicIntegration.description': 'Add personalized music that perfectly matches your video content and mood.',
    'videoRequest.features.musicIntegration.feature1': 'Custom song creation',
    'videoRequest.features.musicIntegration.feature2': 'Mood-based selection',
    'videoRequest.features.musicIntegration.feature3': 'Perfect timing sync',
    'videoRequest.features.aiEffects.title': 'AI Effects',
    'videoRequest.features.aiEffects.description': 'Enhance your videos with AI-powered effects, filters, and animations.',
    'videoRequest.features.aiEffects.feature1': 'Smart filters',
    'videoRequest.features.aiEffects.feature2': 'Motion effects',
    'videoRequest.features.aiEffects.feature3': 'Style transfer',
        'videoRequest.cta.button': 'Start Creating Videos',
 
    // Voice Cloning Section
    'voiceCloning.title': 'Clone Your Voice with AI Technology',
    'voiceCloning.subtitle': 'Create a digital copy of your voice to use in songs, videos, podcasts, and more. Our advanced AI captures the unique characteristics of your voice perfectly.',
    'voiceCloning.features.recording.title': 'Voice Recording',
    'voiceCloning.features.recording.description': 'Record a few minutes of your voice to create a high-quality voice model.',
    'voiceCloning.features.recording.details': 'We recommend 3-5 minutes of clear speech in a quiet environment',
    'voiceCloning.features.processing.title': 'AI Processing',
    'voiceCloning.features.processing.description': 'Our AI analyzes your voice patterns and creates a digital voice clone.',
    'voiceCloning.features.processing.details': 'Advanced neural networks capture tone, pitch, and unique characteristics',
    'voiceCloning.features.integration.title': 'Voice Integration',
    'voiceCloning.features.integration.description': 'Use your cloned voice in songs, videos, and other creative projects.',
    'voiceCloning.features.integration.details': 'Perfect for personalized content, presentations, and entertainment',
    'voiceCloning.cta.title': 'Start Voice Cloning',
    'voiceCloning.cta.description': 'Record your voice and let AI create your digital voice twin',
    'voiceCloning.cta.button': 'Start Recording',
  },
  nl: {
    // Hero Section
    'hero.subtitle': 'Maak gepersonaliseerde liedjes voor je speciale momenten. Van bruiloften tot verjaardagen, maak elke viering onvergetelijk.',
    'hero.button': 'Liedje Maken',
    'hero.process': 'Eenvoudig: Prompt → Genereer → Betaal → Geniet',
    'hero.aiPowered': 'AI-aangedreven muziekcreëring',
    'hero.trust.fastDelivery': 'Snelle levering',
    'hero.trust.studioQuality': 'Studio kwaliteit stemmen',
    'hero.trust.royaltySafe': 'Telifrecht veilig',
    'hero.overlay.weddingSpecial': 'Huwelijksspeciaal',
    'hero.overlay.perfectForFirstDance': 'Perfect voor je eerste dans',
    'hero.slide1.title': 'Maak je eerste dans echt jouw',
    'hero.slide1.subtitle': 'Creëer een gepersonaliseerd liedje dat de essentie van je speciale moment vastlegt. Van eerste dansen tot huwelijksaanbevelingen, maak elke viering onvergetelijk.',
    'hero.slide2.title': 'Elke verjaardag verdient een thema-liedje',
    'hero.slide2.subtitle': 'Transformeer je verjaardag in een muzikale viering met een gepersonaliseerd liedje dat je verhaal vertelt. Perfect voor verjaardagsmilestones en speciale gelegenheden.',
    'hero.slide3.title': 'Vier je liefdesverhaal in lied',
    'hero.slide3.subtitle': 'Markeer je reis samen met een mooi, gepersonaliseerd liedje. Elk jaar verdient zijn eigen melodie.',
    'hero.slide4.title': 'Maak je aanbeveling onvergetelijk',
    'hero.slide4.subtitle': 'Creëer een perfecte stemming voor je liefdesverhaal met een gepersonaliseerd liedje. Maak het oneindig lang met onvergetelijke herinneringen.',
    'hero.slide5.title': 'Vier je succes in lied',
    'hero.slide5.subtitle': 'Markeer je afstuderen, afstuderen of elke hoogtepunt met een gepersonaliseerd mars dat je succes en je reis presteert.',
    
    // Navigation
    'nav.services': 'Diensten',
    'nav.howItWorks': 'Hoe Het Werkt',
    'nav.requestSong': 'Liedje Aanvraag',
    'nav.requestVideo': 'Video Aanvraag',
    'nav.getStarted': 'Start',
    
    // Services
    'services.title': 'Onze Diensten',
    'services.subtitle': 'We bieden gepersonaliseerde AI-aangedreven diensten voor je speciale momenten.',
    'services.paymentInfo.title': 'Betalingsinformatie',
    'services.paymentInfo.description': 'Betaling gebeurt wanneer je je prompt indient. Inclusief tot 2 hergeneraties als je niet tevreden bent.',
    'services.paymentInfo.step1': 'Dien je prompt in',
    'services.paymentInfo.step2': 'Doe betaling',
    'services.paymentInfo.step3': 'Krijg je liedje',
    
    // Service Details
    'services.songCreation.title': 'Aangepaste Liedjes Maken',
    'services.songCreation.description': 'AI-aangedreven gepersonaliseerde liedjes voor je speciale momenten',
    'services.songCreation.price': '500 TL',
    'services.songCreation.priceNote': 'per liedje',
    'services.songCreation.feature1': 'Aangepaste teksten en melodie',
    'services.songCreation.feature2': 'Meerdere genre-opties',
    'services.songCreation.feature3': 'Tot 3 revisies per liedje',
    'services.songCreation.feature4': 'Hoogwaardig audiobestand',
    'services.songCreation.feature5': 'Persoonlijke gebruiksrechten',
    'services.songCreation.feature6': 'Levering tot 5 minuten',
    
    'services.voiceCloning.title': 'Stem Klonen',
    'services.voiceCloning.description': 'Maak een perfecte replica van je stem voor zingen',
    'services.voiceCloning.price': '250 TL',
    'services.voiceCloning.priceNote': 'per stemkloon',
    'services.voiceCloning.feature1': 'Professionele stemanalyse',
    'services.voiceCloning.feature2': 'Hoogwaardige stemkloon',
    'services.voiceCloning.feature3': 'Meerdere stemvariaties',
    'services.voiceCloning.feature4': 'Trainingsgegevens inbegrepen',
    'services.voiceCloning.feature5': 'API-toegang voor toekomstig gebruik',
    'services.voiceCloning.feature6': 'Levering tot 5 minuten',
    
    'services.videoAnimation.title': 'Foto/Video Animatie',
    'services.videoAnimation.description': 'Breng je foto\'s tot leven met AI-animatie',
    'services.videoAnimation.price': '500 TL',
    'services.videoAnimation.priceNote': 'per video',
    'services.videoAnimation.feature1': 'AI-aangedreven animatie',
    'services.videoAnimation.feature2': 'Meerdere stijl-opties',
    'services.videoAnimation.feature3': 'Aangepaste videoscenario\'s',
    'services.videoAnimation.feature4': 'Hoge resolutie output',
    'services.videoAnimation.feature5': 'Ondersteuning voor meerdere formaten',
    'services.videoAnimation.feature6': 'Levering tot 5 minuten',
    
    // Pricing
    'pricing.payPerUse.name': 'Per Gebruik Betalen',
    'pricing.payPerUse.price': '500 TL',
    'pricing.payPerUse.description': 'Betaling gebeurt wanneer je je prompt indient. Inclusief tot 2 hergeneraties als je niet tevreden bent.',
    'pricing.payPerUse.feature1': 'Liedje maken: 500 TL',
    'pricing.payPerUse.feature2': 'Stem klonen: 250 TL',
    'pricing.payPerUse.feature3': 'Video animatie: 500 TL',
    'pricing.payPerUse.feature4': 'Premium kwaliteit output',
    'pricing.payPerUse.feature5': '2 hergeneratie rechten',
    'pricing.payPerUse.button': 'Begin met Liedje Maken',
    
    // Payment Information
    'payment.title': 'Betalingsinformatie',
    'payment.description': 'Betaling gebeurt wanneer je je prompt indient. Inclusief tot 2 hergeneraties als je niet tevreden bent. We accepteren betalingen in Turkse Lira (TL).',
    'payment.pricing.title': 'Serviceprijzen (TL)',
    'payment.songGeneration': 'Liedjes Genereren: 500 TL',
    'payment.voiceCloning': 'Stem Klonen: 250 TL',
    'payment.videoCreation': 'Video Maken: 500 TL',
    'payment.gateways.title': 'Betaalpoorten',
    'payment.iyzico': 'Veilige Turkse betaalpoort',
    'payment.paytr': 'Alternatieve Turkse betaaloplossing',
    'payment.comingSoon': 'Binnenkort Beschikbaar',
    'payment.accountsOpening': 'Betaalrekeningen worden momenteel geopend',
    
    // How It Works
    'howItWorks.title': 'Hoe Het Werkt',
    'howItWorks.subtitle': '3 Eenvoudige Stappen',
    'howItWorks.description': 'Van idee tot voltooid liedje in minuten. Ons AI-aangedreven platform maakt het maken van gepersonaliseerde muziek net zo eenvoudig als het beschrijven van je visie.',
    'howItWorks.step1.title': 'Beschrijf Je Visie',
    'howItWorks.step1.description': 'Vertel ons over je speciale moment, de stemming die je wilt en alle specifieke details die voor jou belangrijk zijn.',
    'howItWorks.step2.title': 'AI Maakt Je Liedje',
    'howItWorks.step2.description': 'Onze geavanceerde AI analyseert je visie en componeert een uniek, gepersonaliseerd liedje speciaal voor jou.',
    'howItWorks.step3.title': 'Bekijk en Perfectioneer',
    'howItWorks.step3.description': 'Luister naar je liedje en genereer opnieuw indien nodig. Krijg het precies goed met ons 3-pogingen systeem.',
    'howItWorks.learnMore': 'Meer Informatie',
    'howItWorks.cta.title': 'Begin Nu',
    'howItWorks.cta.description': 'Klaar om je speciale momenten onvergetelijk te maken?',
    'howItWorks.cta.button': 'Begin met Liedje Maken',
    
    // Footer
    'footer.description': 'We maken gepersonaliseerde liedjes en video\'s die je speciale momenten onvergetelijk maken. Aangedreven door de nieuwste AI-technologieën inclusief Suno API, KITS AI en RunwayML.',
    'footer.features.aiMusic': 'AI Muziek',
    'footer.features.multiLanguage': 'Meertalig',
    'footer.features.fastDelivery': 'Snelle Levering',
    'footer.quickLinks.title': 'Snelle Links',
    'footer.quickLinks.howItWorks': 'Hoe Het Werkt',
    'footer.quickLinks.createSong': 'Liedje Maken',
    'footer.quickLinks.aboutUs': 'Over Ons',
    'footer.quickLinks.contact': 'Contact',
    'footer.contact.title': 'Contact',
    'footer.privacyPolicy': 'Privacybeleid',
    'footer.termsOfService': 'Gebruiksvoorwaarden',
    'footer.poweredBy.text': 'Aangedreven door',
    'footer.poweredBy.aiTechnology': 'AI Technologie',
    'footer.location': 'Istanbul, Turkey',
    'footer.copyright': '© 2024 SongCreator. All rights reserved.',
    'footer.categories.services': 'Diensten',
    'footer.categories.company': 'Bedrijf',
    'footer.categories.support': 'Ondersteuning',
    'footer.categories.resources': 'Bronnen',
    'footer.services.songCreation': 'Aangepaste Liedjes Maken',
    'footer.services.voiceCloning': 'Stem Klonen',
    'footer.services.videoAnimation': 'Foto/Video Animatie',


    'footer.company.aboutUs': 'Over Ons',

    'footer.company.contact': 'Contact',
    'footer.support.helpCenter': 'Hulpcentrum',
    'footer.support.termsOfService': 'Gebruiksvoorwaarden',
    'footer.support.privacyPolicy': 'Privacybeleid',


    'footer.resources.examplesGallery': 'Voorbeelden Galerij',
    'footer.resources.pricingCalculator': 'Prijsberekenaar',
    
    // Song Form
    'songForm.title': 'Maak Je Perfecte Liedje',
    'songForm.subtitle': 'Vertel ons over je visie en we maken een gepersonaliseerd liedje dat je emoties perfect vastlegt.',
    'songForm.header.title': 'Begin Met Liedje Maken',
    'songForm.header.subtitle': 'Vul het formulier hieronder in om te beginnen',
    'songForm.fields.fullName': 'Volledige Naam *',
    'songForm.fields.email': 'E-mail *',
    'songForm.fields.songDescription': 'Liedjestijl *',
    'songForm.fields.occasion': 'Speciale Gelegenheid *',
    'songForm.fields.musicalStyle': 'Stemming *',
    'songForm.fields.mood': 'Stemming *',
    'songForm.fields.tempo': 'Tempo *',
    'songForm.fields.language': 'Taal *',
    'songForm.fields.songLength': 'Liedjelengte *',
    'songForm.fields.specialInstructions': 'Aanvullende Notities',
    'songForm.fields.referenceSongs': 'Referenties (Optioneel)',
    'songForm.placeholders.fullName': 'Voer je volledige naam in',
    'songForm.placeholders.email': 'your.email@example.com',
    'songForm.placeholders.songDescription': 'Vertel ons over je speciale moment, de stemming die je wilt en de emoties die je wilt uitdrukken...',
    'songForm.placeholders.specialInstructions': 'Wil je specifieke instrumenten, stemstijlen of elementen toevoegen? (bijv. "Voeg piano solo toe", "Vrouwelijke stem", "Voeg strijkinstrumenten toe", "Dansbaar arrangement")',
    'songForm.placeholders.referenceSongs': 'bijv. "Like Ed Sheeran\'s Perfect" of "Gelijkaardig aan Adele\'s stijl"',
    'songForm.helpText.songDescription': 'Wees zo specifiek mogelijk! Voeg de specifieke emoties, herinneringen of verhalen die je in het liedje wilt opnemen.',
    'songForm.helpText.specialInstructions': 'Optioneel: Voeg specifieke muziekelementen, instrumenten of stemstijlen toe.',
    'songForm.helpText.referenceSongs': 'Geef aan welke liedjes of artiesten je leuk vindt voor referentie (optioneel).',
    'songForm.submitButton': 'Verzoek Indienen',
    'songForm.responseTime': 'We bekijken je verzoek en nemen binnen 24 uur contact met je op',
    
    // Voice Form
    'voiceForm.title': 'Kloon Je Stem',
    'voiceForm.subtitle': 'Zing je gevoelens met je eigen gekloonde stem. Upload een voorbeeld en we maken een perfecte replica.',
    'voiceForm.nameLabel': 'Volledige Naam *',
    'voiceForm.emailLabel': 'E-mail *',
    'voiceForm.purposeLabel': 'Doel van Stemklonen *',
    'voiceForm.audioSampleLabel': 'Audio Voorbeeld *',
    'voiceForm.additionalNotesLabel': 'Aanvullende Notities',
    'voiceForm.namePlaceholder': 'Voer je volledige naam in',
    'voiceForm.emailPlaceholder': 'your.email@example.com',
    'voiceForm.selectPurpose': 'Selecteer het doel',
    'voiceForm.uploadAudioPrompt': 'Upload je audio voorbeeld',
    'voiceForm.supportedFormats': 'Ondersteunde formaten: MP3, WAV, M4A (Max 10MB)',
    'voiceForm.chooseAudioFile': 'Kies Audio Bestand',
    'voiceForm.changeFile': 'Wijzig Bestand',
    'voiceForm.removeFile': 'Verwijder',
    'voiceForm.audioNotSupported': 'Je browser ondersteunt het audio element niet.',
    'voiceForm.requirements': 'Vereisten:',
    'voiceForm.requirementsDescription': 'Duidelijke spraak/gezang, minimale achtergrondruis, 30+ seconden aanbevolen',
    'voiceForm.additionalNotesPlaceholder': 'Specifieke vereisten of notities over je stemklonen project...',
    'voiceForm.dataPrivacyTitle': 'Gegevensbescherming en Toestemming',
    'voiceForm.dataPrivacyDescription': 'Door je audio voorbeeld te verstrekken, geef je toestemming voor de verwerking en opslag van je stemgegevens voor het doel van het maken van een stemkloon. Je gegevens worden behandeld in overeenstemming met GDPR-voorschriften en worden alleen gebruikt voor het gespecificeerde doel. Je hebt het recht om op elk moment verwijdering van je gegevens te verzoeken.',
    'voiceForm.gdprConsent': 'Ik geef toestemming voor de verwerking en opslag van mijn stemgegevens voor stemklonen doeleinden, en ik begrijp mijn rechten onder GDPR-voorschriften.',
    'voiceForm.consentAlert': 'Geef alstublieft toestemming voor gegevensopslag en -verwerking.',
    'voiceForm.processingMessage': 'Je Verzoek Wordt Verwerkt...',
    'voiceForm.startVoiceCloning': 'Begin met Stemklonen',
    'voiceForm.responseTime': 'We analyseren je audio en nemen binnen 48 uur contact met je op',
    'voiceForm.purposes.personal': 'Persoonlijke liedjes opname',
    'voiceForm.purposes.podcast': 'Podcast vertelling',
    'voiceForm.purposes.audiobook': 'Audioboek vertelling',
    'voiceForm.purposes.voiceActing': 'Stemacteren',
    'voiceForm.purposes.assistant': 'Persoonlijke assistent stem',
    'voiceForm.purposes.other': 'Anders',
    
    // Photo/Video Form
    'photoVideoForm.bringYourPhotos': 'Breng Je Foto\'s Tot Leven',
    'photoVideoForm.turnYourPhotosIntoMovingVideos': 'Verander je foto\'s in bewegende video\'s en maak indrukwekkende muziekvideo clips met AI-aangedreven animatie.',
    'photoVideoForm.fullName': 'Volledige Naam *',
    'photoVideoForm.email': 'E-mail *',
    'photoVideoForm.photosVideos': 'Foto\'s en Video\'s *',
    'photoVideoForm.animationStyle': 'Animatiestijl',
    'photoVideoForm.desiredDuration': 'Gewenste Duur',
    'photoVideoForm.animationPrompt': 'Animatie Aanwijzing *',
    'photoVideoForm.videoScenario': 'Video Scenario',
    'photoVideoForm.additionalNotes': 'Aanvullende Notities',
    'photoVideoForm.enterYourFullName': 'Voer je volledige naam in',
    'photoVideoForm.yourEmailExample': 'your.email@example.com',
    'photoVideoForm.uploadYourPhotosVideos': 'Upload je foto\'s en video\'s',
    'photoVideoForm.supportedFormats': 'Ondersteunde formaten: JPG, PNG, MP4, MOV (Max 50MB totaal)',
    'photoVideoForm.chooseFiles': 'Kies Bestanden',
    'photoVideoForm.addMoreFiles': 'Voeg Meer Bestanden Toe',
    'photoVideoForm.requirements': 'Vereisten',
    'photoVideoForm.highQualityImagesVideos': 'Hoogwaardige afbeeldingen/video\'s, goede belichting, duidelijke onderwerpen',
    'photoVideoForm.chooseAstyle': 'Kies een stijl',
    'photoVideoForm.selectDuration': 'Selecteer duur',
    'photoVideoForm.describeHowYouWantYourPhotosToMove': 'Beschrijf hoe je wilt dat je foto\'s bewegen en animeren. Wees specifiek over bewegingen, effecten en overgangen...',
    'photoVideoForm.describeTheOverallVideoConcept': 'Beschrijf het algemene videoconcept, verhaal of stemming die je wilt creëren...',
    'photoVideoForm.anySpecificRequirements': 'Specifieke vereisten, referenties of speciale verzoeken voor je video...',
    'photoVideoForm.dataPrivacyConsent': 'Gegevensbescherming en Toestemming',
    'photoVideoForm.consentDescription': 'Door je mediabestanden te uploaden, geef je toestemming voor de verwerking en opslag van je inhoud voor het doel van het maken van geanimeerde video\'s. Je gegevens worden behandeld in overeenstemming met GDPR-voorschriften en worden alleen gebruikt voor het gespecificeerde doel. Je hebt het recht om op elk moment verwijdering van je gegevens te verzoeken.',
    'photoVideoForm.consentCheckboxText': 'Ik geef toestemming voor de verwerking en opslag van mijn mediabestanden voor videomaken doeleinden, en ik begrijp mijn rechten onder GDPR-voorschriften. *',
    'photoVideoForm.consentAlert': 'Geef alstublieft toestemming voor gegevensopslag en -verwerking.',
    'photoVideoForm.processingYourRequest': 'Je Verzoek Wordt Verwerkt...',
    'photoVideoForm.createMyVideo': 'Maak Mijn Video',
    'photoVideoForm.reviewYourRequest': 'We bekijken je verzoek en nemen binnen 48 uur contact met je op',
    'photoVideoForm.styles.cinematic': 'Cinematisch',
    'photoVideoForm.styles.romantic': 'Romantisch',
    'photoVideoForm.styles.adventure': 'Avontuur',
    'photoVideoForm.styles.fantasy': 'Fantasy',
    'photoVideoForm.styles.documentary': 'Documentaire',
    'photoVideoForm.styles.artistic': 'Artistiek',
    'photoVideoForm.styles.modern': 'Modern',
    'photoVideoForm.styles.vintage': 'Vintage',
    'photoVideoForm.styles.minimalist': 'Minimalistisch',
    'photoVideoForm.styles.dynamic': 'Dynamisch',
    'photoVideoForm.durations.short': '15-30 seconden',
    'photoVideoForm.durations.medium': '30-60 seconden',
    'photoVideoForm.durations.long': '1-2 minuten',
    'photoVideoForm.durations.mediumLong': '2-3 minuten',
    'photoVideoForm.durations.longer': '3-5 minuten',
    
    // Video Request Section
    'videoRequest.title': 'AI Sihri ile Kişiselleştirilmiş Videolar Oluşturun',
    'videoRequest.subtitle': 'Fotoğraflarınızı AI üretimi müzik, efektler ve animasyonlarla etkileyici videolara dönüştürün. Sosyal medya, sunumlar ve özel anılar için mükemmel.',
    'videoRequest.features.photoToVideo.title': 'Fotoğraftan Videoya',
    'videoRequest.features.photoToVideo.description': 'Fotoğraflarınızı pürüzsüz geçişler ve efektlerle etkileyici videolara dönüştürün.',
    'videoRequest.features.photoToVideo.feature1': 'AI üretimi geçişler',
    'videoRequest.features.photoToVideo.feature2': 'Özel müzik overlay',
    'videoRequest.features.photoToVideo.feature3': 'Profesyonel efektler',
    'videoRequest.features.musicIntegration.title': 'Müzik Entegrasyonu',
    'videoRequest.features.musicIntegration.description': 'Video içeriğiniz ve ruh halinizle mükemmel şekilde eşleşen kişiselleştirilmiş müzik ekleyin.',
    'videoRequest.features.musicIntegration.feature1': 'Özel şarkı oluşturma',
    'videoRequest.features.musicIntegration.feature2': 'Ruh haline dayalı seçim',
    'videoRequest.features.musicIntegration.feature3': 'Mükemmel zamanlama senkronizasyonu',
    'videoRequest.features.aiEffects.title': 'AI Efektleri',
    'videoRequest.features.aiEffects.description': 'Videolarınızı AI destekli efektler, filtreler ve animasyonlarla geliştirin.',
    'videoRequest.features.aiEffects.feature1': 'Akıllı filtreler',
    'videoRequest.features.aiEffects.feature2': 'Hareket efektleri',
    'videoRequest.features.aiEffects.feature3': 'Stil transferi',
    'videoRequest.cta.button': 'Video Oluşturmaya Başla',

    // Voice Cloning Section
    'voiceCloning.title': 'AI Teknolojisi ile Sesinizi Klonlayın',
    'voiceCloning.subtitle': 'Şarkılar, videolar, podcast\'ler ve daha fazlası için sesinizin dijital kopyasını oluşturun. Gelişmiş AI\'mız sesinizin benzersiz özelliklerini mükemmel şekilde yakalar.',
    'voiceCloning.features.recording.title': 'Ses Kaydı',
    'voiceCloning.features.recording.description': 'Yüksek kaliteli bir ses modeli oluşturmak için sesinizi birkaç dakika kaydedin.',
    'voiceCloning.features.recording.details': 'Sessiz bir ortamda 3-5 dakika net konuşma öneriyoruz',
    'voiceCloning.features.processing.title': 'AI İşleme',
    'voiceCloning.features.processing.description': 'AI\'mız ses kalıplarınızı analiz eder ve dijital ses klonunuzu oluşturur.',
    'voiceCloning.features.processing.details': 'Gelişmiş sinir ağları ton, perde ve benzersiz özellikleri yakalar',
    'voiceCloning.features.integration.title': 'Ses Entegrasyonu',
    'voiceCloning.features.integration.description': 'Klonlanmış sesinizi şarkılarda, videolarda ve diğer yaratıcı projelerde kullanın.',
    'voiceCloning.features.integration.details': 'Kişiselleştirilmiş içerik, sunumlar ve eğlence için mükemmel',
    'voiceCloning.cta.title': 'Ses Klonlamaya Başlayın',
    'voiceCloning.cta.description': 'Sesinizi kaydedin ve AI\'nın dijital ses ikizinizi oluşturmasına izin verin',
    'voiceCloning.cta.button': 'Kayıt Yapmaya Başla',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('tr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && translations[savedLanguage as keyof typeof translations]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (newLanguage: string) => {
    if (translations[newLanguage as keyof typeof translations]) {
      setLanguage(newLanguage);
      localStorage.setItem('language', newLanguage);
    }
  };

  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations];
    return langTranslations?.[key as keyof typeof langTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
